"""Bootstrap default CVP service agreement template and document settings (idempotent)."""

from __future__ import annotations

import logging
import uuid
from datetime import datetime, timezone
from typing import Any, Dict

from database import database
from models.agreements import (
    COL_AGREEMENT_TEMPLATES,
    COL_AGREEMENT_TEMPLATE_VERSIONS,
    COL_SYSTEM_DOCUMENT_SETTINGS,
    DEFAULT_TEMPLATE_CODE,
)
from services.agreement_catalog_service import SETTINGS_DOC_ID

logger = logging.getLogger(__name__)


def _utc() -> str:
    return datetime.now(timezone.utc).isoformat().replace("+00:00", "Z")


DEFAULT_BLOCKS: list[dict[str, Any]] = [
    {
        "key": "parties",
        "label": "Parties",
        "type": "rich_text",
        "required": True,
        "order": 1,
        "enabled": True,
        "content": (
            "{{parties_statement}} Primary client contact email: "
            "{{client_email}}. Primary property or correspondence address: {{client_address}}."
        ),
    },
    {
        "key": "service_scope",
        "label": "Service Scope",
        "type": "rich_text",
        "required": True,
        "order": 2,
        "enabled": True,
        "content": (
            "The Provider supplies access to the Compliance Vault Pro platform and related compliance management "
            "services. Services may include document storage, compliance tracking, reminder notifications, compliance "
            "workflow tools, audit preparation support, and compliance monitoring features connected to residential "
            "property compliance management activities. The service is intended to assist the Client with organising "
            "and monitoring compliance-related information and obligations. The Provider does not provide legal advice, "
            "regulatory approval, or any guarantee that use of the platform alone will ensure full legal or regulatory compliance."
        ),
    },
    {
        "key": "client_responsibilities",
        "label": "Client Responsibilities",
        "type": "rich_text",
        "required": True,
        "order": 3,
        "enabled": True,
        "content": (
            "The Client is responsible for ensuring all uploaded documents, certificates, tenancy information, "
            "property records, licences, inspection reports, and related compliance data are accurate, complete, "
            "and kept up to date. The Client remains solely responsible for obtaining required inspections, licences, "
            "certifications, and professional assessments; acting on compliance alerts, expiry notices, recommendations, "
            "or identified risks; maintaining safe and legally compliant properties; and verifying uploaded documents remain valid."
        ),
        "nodes": [
            {
                "type": "paragraph",
                "text": "The Client is responsible for ensuring all uploaded documents and compliance data are accurate, complete, and up to date.",
            },
            {
                "type": "bullet_list",
                "items": [
                    "obtaining required inspections, licences, certifications, and professional assessments where applicable",
                    "acting on compliance alerts, expiry notices, recommendations, or identified risks",
                    "maintaining safe and legally compliant properties",
                    "verifying that uploaded documents remain valid and applicable",
                ],
            },
        ],
    },
    {
        "key": "plan_fees",
        "label": "Plan and Fees",
        "type": "rich_text",
        "required": True,
        "order": 4,
        "enabled": True,
        "content": (
            "The Client has selected the {{plan_name}} plan billed on a monthly basis at "
            "{{monthly_fee}} {{currency}}. {{onboarding_fee_line}}. "
            "Recurring subscription charges may continue automatically unless cancelled in accordance with billing terms."
        ),
    },
    {
        "key": "compliance_limitation",
        "label": "Compliance Limitation",
        "type": "rich_text",
        "required": True,
        "order": 5,
        "enabled": True,
        "content": (
            "Compliance alerts, reminders, scores, summaries, timelines, audit outputs, risk indicators, or status labels "
            "generated by the platform are informational tools intended to support compliance management workflows. "
            "Such outputs do not constitute legal certification, legal advice, regulatory approval, or confirmation "
            "that a property is fully compliant with all applicable laws or regulations. Final responsibility remains with the Client."
        ),
    },
    {
        "key": "document_handling",
        "label": "Document Records and Data Handling",
        "type": "rich_text",
        "required": True,
        "order": 6,
        "enabled": True,
        "content": (
            "The Provider may store uploaded compliance records, documents, certificates, and related operational data "
            "in accordance with platform privacy, retention, and operational policies."
        ),
    },
    {
        "key": "service_availability",
        "label": "Service Availability",
        "type": "rich_text",
        "required": True,
        "order": 7,
        "enabled": True,
        "content": (
            "The Provider may update, improve, maintain, suspend, or modify parts of the platform where reasonably "
            "necessary for operational, security, compliance, or technical reasons. Reasonable efforts will be made "
            "to maintain service availability, but uninterrupted access cannot be guaranteed."
        ),
    },
    {
        "key": "termination",
        "label": "Termination",
        "type": "rich_text",
        "required": True,
        "order": 8,
        "enabled": True,
        "content": (
            "Either party may terminate the service relationship in accordance with subscription, cancellation, or "
            "termination terms associated with the selected plan."
        ),
    },
    {
        "key": "governing_law",
        "label": "Governing Law",
        "type": "rich_text",
        "required": True,
        "order": 9,
        "enabled": True,
        "content": "This Agreement shall be governed by and interpreted in accordance with the laws of Scotland.",
    },
    {
        "key": "electronic_acceptance",
        "label": "Electronic acceptance",
        "type": "rich_text",
        "required": True,
        "order": 10,
        "enabled": True,
        "content": (
            "{{acceptance_electronic_record_line}} "
            "Named signatory for electronic acceptance: {{accepted_signatory_name}}. "
            "Agreement version {{agreement_version}}."
        ),
    },
]


async def ensure_default_agreement_assets() -> None:
    db = database.get_db()
    existing = await db[COL_AGREEMENT_TEMPLATES].find_one(
        {"code": DEFAULT_TEMPLATE_CODE},
        {"_id": 0, "template_id": 1, "current_published_version_id": 1},
    )
    if existing and existing.get("template_id"):
        # If an older lightweight published version exists, publish an upgraded enterprise copy.
        current_vid = str(existing.get("current_published_version_id") or "")
        current_ver = (
            await db[COL_AGREEMENT_TEMPLATE_VERSIONS].find_one(
                {"version_id": current_vid, "template_id": existing.get("template_id")},
                {"_id": 0, "content_blocks": 1, "version_number": 1},
            )
            if current_vid
            else None
        )
        current_keys = {str((b or {}).get("key") or "") for b in (current_ver or {}).get("content_blocks") or []}
        current_blocks = (current_ver or {}).get("content_blocks") or []
        current_blob = " ".join(str((b or {}).get("content") or "") for b in current_blocks).lower()
        _elec_block = next(
            (b for b in current_blocks if str((b or {}).get("key") or "") == "electronic_acceptance"),
            None,
        )
        _elec_txt = str((_elec_block or {}).get("content") or "")
        electronic_acceptance_legacy = (
            "was electronically accepted by" in _elec_txt.lower()
            and "{{acceptance_timestamp}}" in _elec_txt
            and "{{acceptance_electronic_record_line}}" not in _elec_txt
        )
        needs_upgrade = (
            "compliance_limitation" not in current_keys
            or "where applicable" in current_blob
            or "applicable onboarding or setup fees" in current_blob
            or "billed on a {{billing_interval}} basis" in current_blob
            or electronic_acceptance_legacy
        )
        if needs_upgrade:
            new_version_id = str(uuid.uuid4())
            now = _utc()
            next_num = int((current_ver or {}).get("version_number") or 1) + 1
            await db[COL_AGREEMENT_TEMPLATE_VERSIONS].insert_one(
                {
                    "version_id": new_version_id,
                    "template_id": existing.get("template_id"),
                    "version_number": next_num,
                    "status": "published",
                    "title": "Property Compliance Management Agreement",
                    "subtitle": "(Compliance Vault Pro Service)",
                    "content_blocks": DEFAULT_BLOCKS,
                    "placeholders": [],
                    "effective_from": now,
                    "published_at": now,
                    "published_by": {"user_id": "system", "name": "System seed"},
                    "change_notes": "Upgraded enterprise agreement structure (incl. electronic acceptance preview wording)",
                    "created_at": now,
                }
            )
            await db[COL_AGREEMENT_TEMPLATES].update_one(
                {"template_id": existing.get("template_id")},
                {"$set": {"current_published_version_id": new_version_id, "updated_at": now}},
            )
        await db[COL_SYSTEM_DOCUMENT_SETTINGS].update_one(
            {"settings_id": SETTINGS_DOC_ID},
            {
                "$setOnInsert": {
                    "settings_id": SETTINGS_DOC_ID,
                    "provider_company_name": "Pleerity Enterprise Ltd",
                    "provider_tagline": "AI-Driven Solutions & Compliance.",
                    "provider_address": "8 Valley Court, Hamilton ML3 8HW",
                    "provider_email": "info@pleerityenterprise.co.uk",
                    "provider_phone": "02033376060",
                    "provider_signature_image_url": "",
                    "provider_logo_image_url": "",
                    "brand_primary_color": "#0B1D3A",
                    "brand_secondary_color": "#00B8A9",
                    "default_footer_text": "Pleerity Enterprise Ltd – AI-Driven Solutions & Compliance.",
                    "created_at": _utc(),
                }
            },
            upsert=True,
        )
        return

    template_id = str(uuid.uuid4())
    version_id = str(uuid.uuid4())
    now = _utc()

    version_doc: Dict[str, Any] = {
        "version_id": version_id,
        "template_id": template_id,
        "version_number": 1,
        "status": "published",
        "title": "Property Compliance Management Agreement",
        "subtitle": "(Compliance Vault Pro Service)",
        "content_blocks": DEFAULT_BLOCKS,
        "placeholders": [],
        "effective_from": now,
        "published_at": now,
        "published_by": {"user_id": "system", "name": "System seed"},
        "change_notes": "Initial seeded published version",
        "created_at": now,
    }

    template_doc: Dict[str, Any] = {
        "template_id": template_id,
        "code": DEFAULT_TEMPLATE_CODE,
        "name": "Property Compliance Management Agreement",
        "description": "Default recurring agreement for Compliance Vault Pro clients",
        "category": "service_agreement",
        "status": "active",
        "current_published_version_id": version_id,
        "created_at": now,
        "updated_at": now,
        "created_by": {"user_id": "system", "name": "System seed"},
    }

    await db[COL_AGREEMENT_TEMPLATE_VERSIONS].insert_one(version_doc)
    await db[COL_AGREEMENT_TEMPLATES].insert_one(template_doc)

    await db[COL_SYSTEM_DOCUMENT_SETTINGS].update_one(
        {"settings_id": SETTINGS_DOC_ID},
        {
            "$setOnInsert": {
                "settings_id": SETTINGS_DOC_ID,
                "provider_company_name": "Pleerity Enterprise Ltd",
                "provider_tagline": "AI-Driven Solutions & Compliance.",
                "provider_address": "8 Valley Court, Hamilton ML3 8HW",
                "provider_email": "info@pleerityenterprise.co.uk",
                "provider_phone": "02033376060",
                "provider_signature_image_url": "",
                "provider_logo_image_url": "",
                "brand_primary_color": "#0B1D3A",
                "brand_secondary_color": "#00B8A9",
                "default_footer_text": "Pleerity Enterprise Ltd – AI-Driven Solutions & Compliance.",
                "created_at": now,
            }
        },
        upsert=True,
    )
    logger.info("Seeded default agreement template %s version %s", DEFAULT_TEMPLATE_CODE, version_id)
