"""
Central branding resolution for Pleerity vs white-label client outputs.

All client-facing PDFs, emails, and portal-facing branding should derive from
``resolve_branding`` (or helpers here) — not ad hoc reads of ``branding_settings``.

Internal-only surfaces use ``BrandingContext.INTERNAL_SYSTEM`` (always Pleerity).
"""
from __future__ import annotations

import html
import logging
import re
from dataclasses import dataclass, field
from enum import Enum
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple

from database import database
from services.account_capability_enforcement import CapabilityEnforcementService
from utils.storage_paths import resolve_data_dir
from utils.branding import (
    COMPANY_NAME,
    PRODUCT_NAME,
    TAGLINE,
    SUPPORT_EMAIL,
    PRIMARY_HEX,
    SECONDARY_HEX,
    get_branding_logo_path,
    get_branding_website_url,
    format_customer_support_footer_html,
)

logger = logging.getLogger(__name__)

DATA_DIR = resolve_data_dir()
BRANDING_LOGOS_PATH = Path(DATA_DIR) / "data" / "branding_logos"

# Email template aliases that must never use tenant/client white-label (platform / staff).
INTERNAL_EMAIL_ALIASES = frozenset(
    {
        "internal-alert",
        "admin-manual",
        "pending-verification-digest",
        "admin-invite",
    }
)

_HEX_RE = re.compile(r"^#([0-9A-Fa-f]{3}|[0-9A-Fa-f]{6})$")


class BrandingContext(str, Enum):
    """Where the branding will be shown."""

    INTERNAL_SYSTEM = "internal_system"  # Staff / system only → Pleerity
    CLIENT_FACING_EMAIL = "client_facing_email"
    CLIENT_DOCUMENT_PDF = "client_document_pdf"
    CLIENT_PORTAL_UI = "client_portal_ui"


class BrandingFallbackReason(str, Enum):
    INTERNAL_CONTEXT = "INTERNAL_CONTEXT_PLEERITY_ONLY"
    PLAN_NO_WHITE_LABEL = "PLAN_NO_WHITE_LABEL"
    SUBSCRIPTION_BLOCKED = "SUBSCRIPTION_BLOCKED"
    WHITE_LABEL_NOT_ENABLED = "WHITE_LABEL_NOT_ENABLED"
    DISABLED_BY_PLAN_RECONCILIATION = "DISABLED_BY_PLAN_RECONCILIATION"
    INCOMPLETE_MISSING_COMPANY_NAME = "INCOMPLETE_MISSING_COMPANY_NAME"
    INCOMPLETE_MISSING_SUPPORT_EMAIL = "INCOMPLETE_MISSING_SUPPORT_EMAIL"
    INCOMPLETE_MISSING_LOGO = "INCOMPLETE_MISSING_LOGO"
    INCOMPLETE_INVALID_PRIMARY_COLOR = "INCOMPLETE_INVALID_PRIMARY_COLOR"
    CLIENT_NOT_FOUND = "CLIENT_NOT_FOUND"


@dataclass
class ResolvedBrandingProfile:
    """Resolved branding for one render. Always complete (no partial client fields)."""

    source: str  # "pleerity" | "client_white_label"
    company_name: str
    """Brand / letterhead name (Pleerity or client WL)."""
    tagline: str
    product_display_name: str
    primary_color: str
    secondary_color: str
    accent_color: str
    text_color: str
    logo_url: Optional[str]
    logo_path: Optional[str]  # Local file for ReportLab, when available
    support_email: str
    support_phone: Optional[str]
    website_url: str
    report_header_text: Optional[str]
    report_footer_text: Optional[str]
    include_pleerity_attribution: bool
    powered_by_text: str  # Single line for footers / attribution policy
    email_from_display_hint: Optional[str]
    email_reply_to: Optional[str]
    fallback_reasons: List[str] = field(default_factory=list)
    context: str = ""
    document_company_name: str = ""
    """Portfolio owner name on report body when using Pleerity letterhead."""

    def to_report_dict(self) -> Dict[str, Any]:
        """Shape expected by ``professional_reports`` / PDF builders."""
        cover = (self.document_company_name or self.company_name).strip() or self.company_name
        return {
            "company_name": cover,
            "brand_company_name": self.company_name,
            "logo_url": self.logo_url,
            "logo_path": self.logo_path,
            "primary_color": self.primary_color,
            "secondary_color": self.secondary_color,
            "accent_color": self.accent_color,
            "text_color": self.text_color,
            "report_header_text": self.report_header_text,
            "report_footer_text": self.report_footer_text,
            "include_pleerity_branding": self.include_pleerity_attribution,
            "contact_email": self.support_email,
            "contact_phone": self.support_phone,
            "website_url": self.website_url,
            "branding_source": self.source,
            "fallback_reasons": list(self.fallback_reasons),
            "pdf_footer_generated_by": self._pdf_generated_by_line(),
            "pdf_footer_contact_line": self._pdf_contact_line(),
            "pdf_attribution_lines": self._pdf_attribution_lines(),
        }

    def _pdf_generated_by_line(self) -> str:
        if self.source == "client_white_label":
            return f"Prepared for {self.company_name}"
        return f"Generated by {COMPANY_NAME}"

    def _pdf_contact_line(self) -> str:
        web = self.website_url or get_branding_website_url()
        return f"{web} | {self.support_email}"

    def _pdf_attribution_lines(self) -> List[str]:
        """Platform attribution lines (no mixed client/Pleerity strings)."""
        if self.source == "pleerity":
            return ["Generated by Compliance Vault Pro • Powered by Pleerity Enterprise"]
        lines = ["Prepared via Compliance Vault Pro"]
        if self.include_pleerity_attribution and self.powered_by_text:
            lines.append(self.powered_by_text)
        return lines

    def to_email_layout_kwargs(self) -> Dict[str, Any]:
        """Kwargs merged into ``build_customer_email_layout`` (explicit args win)."""
        link_color = self.secondary_color or SECONDARY_HEX
        header_bg = self.primary_color or PRIMARY_HEX
        support_footer = format_customer_support_footer_html(link_color)
        if self.source == "client_white_label":
            esc = html.escape(self.support_email)
            support_footer = (
                "If you have any questions, contact us at "
                f'<a href="mailto:{esc}" style="color: {link_color}; text-decoration: none;">{esc}</a>'
            )
            if self.support_phone:
                support_footer += (
                    f"<br/>Phone: {html.escape(self.support_phone)}"
                )

        powered_by_html = ""
        if self.include_pleerity_attribution and self.powered_by_text:
            powered_by_html = (
                f'<p style="color: #94a3b8; font-size: 11px; margin: 8px 0 0 0;">'
                f"{html.escape(self.powered_by_text)}</p>"
            )

        header_logo_block = ""
        if self.logo_url and self.source == "client_white_label":
            esc_url = html.escape(self.logo_url, quote=True)
            header_logo_block = (
                f'<p style="margin: 0 0 12px 0;"><img src="{esc_url}" alt="" '
                'style="max-height: 48px; max-width: 200px;" /></p>'
            )

        return {
            "company_name": self.company_name,
            "tagline": self.tagline,
            "support_email": self.support_email,
            "website_url": self.website_url,
            "header_bg": header_bg,
            "link_color": link_color,
            "support_footer_html": support_footer,
            "powered_by_html": powered_by_html,
            "header_logo_html": header_logo_block,
            "security_note": (
                f"For security, {self.company_name} and Pleerity will never ask for your password by email."
                if self.source == "client_white_label"
                else "For security, Pleerity will never ask for your password by email."
            ),
        }

    def to_template_renderer_dict(self) -> Dict[str, Any]:
        """Letterhead/footer for order DOCX/PDF (``template_renderer``)."""
        rd = self.to_report_dict()
        return {
            "header_banner_company": self.company_name.upper()
            if self.source == "pleerity"
            else self.company_name,
            "primary_hex": self.primary_color,
            "secondary_hex": self.secondary_color,
            "footer_generated_line": rd["pdf_footer_generated_by"],
            "footer_contact_line": rd["pdf_footer_contact_line"],
            "support_email": self.support_email,
        }

    def to_order_email_branding_dict(self) -> Dict[str, Any]:
        """Strip colours and identity for ``order_email_templates``."""
        return {
            "header_bg": self.primary_color,
            "accent": self.secondary_color,
            "company_name": self.company_name,
            "tagline": self.tagline,
            "support_email": self.support_email,
        }

    def to_portal_dict(self) -> Dict[str, Any]:
        """Resolved branding for client portal UI."""
        return {
            "source": self.source,
            "company_name": self.company_name,
            "tagline": self.tagline,
            "primary_color": self.primary_color,
            "secondary_color": self.secondary_color,
            "logo_url": self.logo_url,
            "support_email": self.support_email,
            "support_phone": self.support_phone,
            "website_url": self.website_url,
            "include_pleerity_attribution": self.include_pleerity_attribution,
            "powered_by_text": self.powered_by_text,
            "fallback_reasons": list(self.fallback_reasons),
        }


def _valid_hex_color(value: Optional[str]) -> bool:
    if not value or not isinstance(value, str):
        return False
    return bool(_HEX_RE.match(value.strip()))


def _client_logo_file_path(client_id: str, branding_doc: Dict[str, Any]) -> Optional[str]:
    ext = branding_doc.get("logo_upload_ext")
    if not ext or not str(ext).startswith("."):
        return None
    path = BRANDING_LOGOS_PATH / f"{client_id}{ext}"
    if path.is_file():
        return str(path)
    return None


def pleerity_profile(*, context: str = "", document_company_name: str = "") -> ResolvedBrandingProfile:
    """Default Pleerity branding (sync, no I/O)."""
    logo = get_branding_logo_path()
    return ResolvedBrandingProfile(
        source="pleerity",
        company_name=COMPANY_NAME,
        document_company_name=document_company_name or "",
        tagline=TAGLINE,
        product_display_name=PRODUCT_NAME,
        primary_color=PRIMARY_HEX,
        secondary_color=SECONDARY_HEX,
        accent_color="#FFB800",
        text_color="#1F2937",
        logo_url=None,
        logo_path=logo,
        support_email=SUPPORT_EMAIL,
        support_phone=None,
        website_url=get_branding_website_url(),
        report_header_text=None,
        report_footer_text=None,
        include_pleerity_attribution=True,
        powered_by_text=f"{PRODUCT_NAME} · {COMPANY_NAME}",
        email_from_display_hint=None,
        email_reply_to=None,
        fallback_reasons=[],
        context=context,
    )


async def resolve_branding(
    client_id: str,
    context: BrandingContext,
    *,
    asset_path: str = "",
) -> ResolvedBrandingProfile:
    """
    Resolve effective branding for ``client_id``.

    White-label applies only for non-internal contexts, when plan allows,
    ``white_label_enabled`` is true, reconciliation has not disabled WL,
    and required assets (name, support email, logo on disk) are present.
    """
    reasons: List[str] = []
    log_extra = {"client_id": client_id, "context": context.value, "asset_path": asset_path}

    db = database.get_db()
    client = await db.clients.find_one(
        {"client_id": client_id},
        {"_id": 0, "company_name": 1, "full_name": 1, "email": 1, "phone": 1},
    )
    doc_name = (
        (client or {}).get("company_name") or (client or {}).get("full_name") or ""
    ).strip() or "Client"

    if context == BrandingContext.INTERNAL_SYSTEM:
        p = pleerity_profile(context=context.value, document_company_name=doc_name)
        p.fallback_reasons = [BrandingFallbackReason.INTERNAL_CONTEXT.value]
        logger.info("Branding resolved to pleerity: %s", p.fallback_reasons[0], extra=log_extra)
        return p

    if not client:
        p = pleerity_profile(context=context.value)
        p.fallback_reasons = [BrandingFallbackReason.CLIENT_NOT_FOUND.value]
        logger.warning("Branding fallback: client not found", extra=log_extra)
        return p

    branding_doc = await db.branding_settings.find_one({"client_id": client_id}, {"_id": 0}) or {}

    wl_decision = await CapabilityEnforcementService(db).evaluate(
        client_id, "CAP_BRANDING_WHITE_LABEL", "read"
    )
    if not wl_decision.allowed:
        code = wl_decision.reason_code or BrandingFallbackReason.PLAN_NO_WHITE_LABEL.value
        reasons.append(str(code))
        p = _pleerity_with_client_placeholder(client, reasons, context.value, doc_name)
        logger.info(
            "Branding resolved to pleerity (runtime capability): %s",
            reasons,
            extra=log_extra,
        )
        return p

    if branding_doc.get("white_label_disabled_by_plan"):
        reasons.append(BrandingFallbackReason.DISABLED_BY_PLAN_RECONCILIATION.value)
        p = _pleerity_with_client_placeholder(client, reasons, context.value, doc_name)
        logger.info("Branding resolved to pleerity: plan reconciliation flag", extra=log_extra)
        return p

    if not branding_doc.get("white_label_enabled"):
        reasons.append(BrandingFallbackReason.WHITE_LABEL_NOT_ENABLED.value)
        p = _pleerity_with_client_placeholder(client, reasons, context.value, doc_name)
        logger.info("Branding resolved to pleerity: white_label not enabled", extra=log_extra)
        return p

    company_name = (branding_doc.get("company_name") or client.get("company_name") or client.get("full_name") or "").strip()
    if not company_name:
        reasons.append(BrandingFallbackReason.INCOMPLETE_MISSING_COMPANY_NAME.value)
        p = _pleerity_with_client_placeholder(client, reasons, context.value, doc_name)
        logger.info("Branding resolved to pleerity: missing company name", extra=log_extra)
        return p

    support_email = (branding_doc.get("contact_email") or client.get("email") or "").strip()
    if not support_email:
        reasons.append(BrandingFallbackReason.INCOMPLETE_MISSING_SUPPORT_EMAIL.value)
        p = _pleerity_with_client_placeholder(client, reasons, context.value, doc_name)
        return p

    logo_path = _client_logo_file_path(client_id, branding_doc)
    if not logo_path:
        reasons.append(BrandingFallbackReason.INCOMPLETE_MISSING_LOGO.value)
        p = _pleerity_with_client_placeholder(client, reasons, context.value, doc_name)
        logger.info("Branding resolved to pleerity: logo file missing", extra=log_extra)
        return p

    primary = (branding_doc.get("primary_color") or PRIMARY_HEX).strip()
    if not _valid_hex_color(primary):
        reasons.append(BrandingFallbackReason.INCOMPLETE_INVALID_PRIMARY_COLOR.value)
        p = _pleerity_with_client_placeholder(client, reasons, context.value, doc_name)
        return p

    secondary = (branding_doc.get("secondary_color") or SECONDARY_HEX).strip()
    if not _valid_hex_color(secondary):
        secondary = SECONDARY_HEX

    accent = (branding_doc.get("accent_color") or "#FFB800").strip()
    if not _valid_hex_color(accent):
        accent = "#FFB800"

    text_c = (branding_doc.get("text_color") or "#1F2937").strip()
    if not _valid_hex_color(text_c):
        text_c = "#1F2937"

    website = (branding_doc.get("website_url") or "").strip() or get_branding_website_url()
    logo_url = (branding_doc.get("logo_url") or "").strip() or None
    phone = (branding_doc.get("contact_phone") or client.get("phone") or "").strip() or None
    include_pleerity = bool(branding_doc.get("include_pleerity_branding", True))
    powered_by = "Powered by Pleerity Enterprise" if include_pleerity else ""

    profile = ResolvedBrandingProfile(
        source="client_white_label",
        company_name=company_name,
        document_company_name=company_name,
        tagline=TAGLINE,
        product_display_name=PRODUCT_NAME,
        primary_color=primary,
        secondary_color=secondary,
        accent_color=accent,
        text_color=text_c,
        logo_url=logo_url,
        logo_path=logo_path,
        support_email=support_email,
        support_phone=phone,
        website_url=website,
        report_header_text=branding_doc.get("report_header_text"),
        report_footer_text=branding_doc.get("report_footer_text"),
        include_pleerity_attribution=include_pleerity,
        powered_by_text=powered_by,
        email_from_display_hint=branding_doc.get("email_from_name"),
        email_reply_to=branding_doc.get("email_reply_to"),
        fallback_reasons=[],
        context=context.value,
    )
    logger.info(
        "Branding resolved to client_white_label",
        extra={**log_extra, "company_name": company_name},
    )
    return profile


def _pleerity_with_client_placeholder(
    client: Dict[str, Any],
    reasons: List[str],
    context: str,
    document_company_name: str,
) -> ResolvedBrandingProfile:
    """Pleerity letterhead; portfolio owner name on the document body."""
    p = pleerity_profile(context=context, document_company_name=document_company_name)
    p.fallback_reasons = list(reasons)
    return p


async def merge_email_branding_context(
    context: Dict[str, Any],
    alias_str: str,
    client_id: Optional[str],
) -> None:
    """
    Mutates ``context`` with ``_email_branding`` dict for ``build_customer_email_layout``.

    Internal aliases always get Pleerity branding without calling ``resolve_branding``.
    """
    if alias_str in INTERNAL_EMAIL_ALIASES or not client_id:
        p = pleerity_profile(context="email_internal")
        context["_email_branding"] = p.to_email_layout_kwargs()
        context["_branding_resolution"] = {
            "source": p.source,
            "fallback_reasons": [BrandingFallbackReason.INTERNAL_CONTEXT.value] if client_id else ["NO_CLIENT_ID"],
        }
        context["_email_send_extras"] = {}
        return

    if context.get("_force_pleerity_email_branding"):
        p = pleerity_profile(context="platform_broadcast_email")
        context["_email_branding"] = p.to_email_layout_kwargs()
        context["_branding_resolution"] = {
            "source": p.source,
            "fallback_reasons": [BrandingFallbackReason.INTERNAL_CONTEXT.value],
        }
        context["_email_send_extras"] = {}
        return

    profile = await resolve_branding(client_id, BrandingContext.CLIENT_FACING_EMAIL)
    context["_email_branding"] = profile.to_email_layout_kwargs()
    context["_branding_resolution"] = {
        "source": profile.source,
        "fallback_reasons": profile.fallback_reasons,
    }
    extras: Dict[str, Optional[str]] = {}
    if profile.source == "client_white_label":
        rt = (profile.email_reply_to or "").strip()
        fn = (profile.email_from_display_hint or "").strip()
        extras["reply_to"] = rt or None
        extras["from_display_name"] = fn or None
    context["_email_send_extras"] = extras


def merge_invoice_branding_overlay(profile: ResolvedBrandingProfile) -> Dict[str, Any]:
    """Keys consumed by ``invoice_pdf_builder.build_branded_invoice_pdf_bytes``."""
    from utils.branding import TAGLINE as BL_TAGLINE

    website = profile.website_url or get_branding_website_url()
    if profile.source == "client_white_label":
        return {
            "_inv_company_name": profile.company_name,
            "_inv_support_email": profile.support_email,
            "_inv_tagline": profile.tagline or BL_TAGLINE,
            "_inv_website": website,
            "_inv_logo_path": profile.logo_path,
            "_inv_header_bg": profile.primary_color,
            "_inv_accent_hex": profile.secondary_color,
        }
    return {}


async def prepare_invoice_pdf_data_with_branding(
    client_id: Optional[str],
    data: Dict[str, Any],
) -> Dict[str, Any]:
    """Attach branding overlay for order/receipt PDFs when ``client_id`` is known."""
    if not client_id:
        return data
    profile = await resolve_branding(client_id, BrandingContext.CLIENT_DOCUMENT_PDF)
    overlay = merge_invoice_branding_overlay(profile)
    return {**data, **overlay}


async def resolve_order_email_branding(client_id: Optional[str]) -> Dict[str, Any]:
    """Resolved strip for ``order_email_templates`` (Pleerity if no client)."""
    cid = (client_id or "").strip() or None
    if not cid:
        return pleerity_profile().to_order_email_branding_dict()
    p = await resolve_branding(cid, BrandingContext.CLIENT_FACING_EMAIL)
    return p.to_order_email_branding_dict()


def _append_plain_text_branding_footer(text_body: str, context: Dict[str, Any]) -> str:
    eb = context.get("_email_branding")
    if not isinstance(eb, dict):
        return text_body
    co = eb.get("company_name") or COMPANY_NAME
    tag = (eb.get("tagline") or "").strip()
    se = eb.get("support_email") or SUPPORT_EMAIL
    block = f"\n\n--\n{co}\n{tag}\nContact: {se}\n"
    if block.strip() in (text_body or ""):
        return text_body
    return (text_body or "") + block


def _inject_branding_banner_into_full_html(html_body: str, context: Dict[str, Any]) -> str:
    eb = context.get("_email_branding")
    if not isinstance(eb, dict):
        return html_body
    bg = html.escape(eb.get("header_bg") or PRIMARY_HEX)
    fg = html.escape(eb.get("link_color") or SECONDARY_HEX)
    cn = html.escape(eb.get("company_name") or "")
    tg = html.escape(eb.get("tagline") or "")
    logo = eb.get("header_logo_html") or ""
    banner = (
        f'<div style="background-color:{bg};padding:12px 16px;text-align:center;'
        f'font-family:Arial,sans-serif;color:#fff;">{logo}'
        f'<strong style="color:{fg}">{cn}</strong><br/>'
        f'<span style="font-size:12px;opacity:.9">{tg}</span></div>'
    )
    out = re.sub(r"(<body[^>]*>)", r"\1" + banner, html_body, count=1, flags=re.I)
    pb = eb.get("powered_by_html") or ""
    if pb and re.search(r"</body\s*>", out, flags=re.I):
        out = re.sub(r"</body\s*>", pb + r"</body>", out, count=1, flags=re.I)
    return out


def finalize_db_email_html(
    html_body: str,
    text_body: str,
    context: Dict[str, Any],
    alias_str: str,
    client_id: Optional[str],
) -> Tuple[str, str]:
    """
    Apply resolved branding to DB-driven templates: fragment → customer shell;
    full HTML document → banner + optional attribution before </body>.
    """
    if alias_str in INTERNAL_EMAIL_ALIASES or not client_id:
        return html_body, text_body
    stripped = (html_body or "").lstrip()
    if re.search(r"<\s*html[\s>]", stripped, re.I):
        return (
            _inject_branding_banner_into_full_html(html_body, context),
            _append_plain_text_branding_footer(text_body, context),
        )
    from email_presentation.greeting import resolve_greeting, strip_embedded_greetings
    from email_presentation.shell import render_customer_email

    eb = context.get("_email_branding")
    ht = (eb.get("company_name") if isinstance(eb, dict) else None) or "Pleerity"
    greeting = resolve_greeting(
        display_name=context.get("client_name") or context.get("full_name"),
        first_name=context.get("first_name"),
        client_name=context.get("client_name"),
    )
    body = strip_embedded_greetings(html_body or "")
    out_html = render_customer_email(
        context,
        greeting=greeting,
        body_html=body,
        header_title=ht,
        show_preferences_link=bool(context.get("show_preferences_link")),
        preferences_url=context.get("preferences_url"),
    )
    return out_html, _append_plain_text_branding_footer(text_body, context)
