"""
Service Catalogue - Database-driven service definitions.
NO hard-coded service logic - all services must be defined in the catalogue.

This is the authoritative source for:
- What services exist
- What documents they generate
- What intake fields they require
- How they are priced and delivered
"""
from pydantic import BaseModel, Field
from typing import Optional, List, Dict, Any
from enum import Enum
from datetime import datetime, timezone
from database import database
import logging

logger = logging.getLogger(__name__)


# ============================================================================
# ENUMS
# ============================================================================

class ServiceCategory(str, Enum):
    """Service category - determines where service appears and how it's sold."""
    CVP_FEATURE = "CVP_FEATURE"           # Core CVP functionality (included in plans)
    CVP_ADDON = "CVP_ADDON"               # Add-on to CVP subscription
    STANDALONE_REPORT = "STANDALONE_REPORT"  # Standalone purchasable report
    DOCUMENT_PACK = "DOCUMENT_PACK"       # Legal/operational document bundle


class PricingModel(str, Enum):
    """How the service is priced."""
    ONE_TIME = "one_time"       # Single purchase
    SUBSCRIPTION = "subscription"  # Recurring
    ADDON = "addon"             # Add-on to existing subscription
    INCLUDED = "included"       # Included in plan (no additional charge)


class DeliveryType(str, Enum):
    """How deliverables are provided to the customer."""
    PORTAL = "portal"           # Available in client portal only
    EMAIL = "email"             # Emailed directly
    PORTAL_EMAIL = "portal+email"  # Both portal and email


class GenerationMode(str, Enum):
    """How documents are generated for this service."""
    TEMPLATE_ONLY = "TEMPLATE_ONLY"       # Pure template merge (no AI)
    AI_ASSISTED_JSON = "AI_ASSISTED_JSON"  # AI generates JSON, template renders
    HYBRID = "HYBRID"                      # Template + AI enhancement


# ============================================================================
# INTAKE FIELD SCHEMA
# ============================================================================

class IntakeFieldType(str, Enum):
    """Types of intake fields."""
    TEXT = "text"
    TEXTAREA = "textarea"
    NUMBER = "number"
    DATE = "date"
    SELECT = "select"
    MULTI_SELECT = "multi_select"
    CHECKBOX = "checkbox"
    FILE = "file"
    ADDRESS = "address"


class IntakeFieldSchema(BaseModel):
    """Schema for a single intake field."""
    field_id: str
    label: str
    field_type: IntakeFieldType
    required: bool = True
    placeholder: Optional[str] = None
    help_text: Optional[str] = None
    options: Optional[List[str]] = None  # For select/multi_select
    validation_regex: Optional[str] = None
    min_value: Optional[float] = None
    max_value: Optional[float] = None
    default_value: Optional[Any] = None
    order: int = 0


# ============================================================================
# DOCUMENT DEFINITION
# ============================================================================

class DocumentDefinition(BaseModel):
    """Definition of a document generated by a service."""
    document_code: str          # e.g., "SECTION_21_NOTICE"
    document_name: str          # e.g., "Section 21 Notice"
    template_id: Optional[str] = None  # Reference to template
    generation_order: int = 0   # Order in which to generate
    review_order: int = 0       # Order in which to review
    format: str = "pdf"         # pdf, docx, or both
    is_primary: bool = False    # Primary document in pack


# ============================================================================
# SERVICE CATALOGUE ENTRY
# ============================================================================

class ServiceCatalogueEntry(BaseModel):
    """
    Complete service definition.
    This is the authoritative record for what a service is and how it behaves.
    """
    # Identity (immutable after creation)
    service_code: str = Field(..., description="Unique immutable service code")
    
    # Display
    service_name: str
    description: str
    short_description: Optional[str] = None
    icon: Optional[str] = None  # Icon identifier for UI
    
    # Classification
    category: ServiceCategory
    tags: List[str] = []
    
    # Pricing
    pricing_model: PricingModel
    price_amount: int = 0  # In pence/cents
    price_currency: str = "gbp"
    stripe_price_id: Optional[str] = None
    vat_rate: float = 0.20  # 20% UK VAT
    
    # Delivery
    delivery_type: DeliveryType
    estimated_turnaround_hours: int = 24
    
    # Documents
    documents_generated: List[DocumentDefinition] = []
    delivery_format: str = "single_pdf"  # single_pdf, zip_bundle, individual_files
    
    # Intake
    intake_fields: List[IntakeFieldSchema] = []
    
    # Review & Generation
    review_required: bool = True
    generation_mode: GenerationMode = GenerationMode.TEMPLATE_ONLY
    master_prompt_version: Optional[str] = None  # Version of master prompt to use
    
    # Entitlements
    requires_cvp_subscription: bool = False
    allowed_plans: List[str] = []  # Empty = all plans, otherwise restrict
    
    # Status
    active: bool = True
    display_order: int = 0  # For UI ordering
    
    # Audit
    created_at: Optional[datetime] = None
    updated_at: Optional[datetime] = None
    created_by: Optional[str] = None
    updated_by: Optional[str] = None

    def to_dict(self) -> Dict[str, Any]:
        """Convert to dictionary for MongoDB storage."""
        data = self.model_dump()
        # Convert enums to values
        data["category"] = self.category.value
        data["pricing_model"] = self.pricing_model.value
        data["delivery_type"] = self.delivery_type.value
        data["generation_mode"] = self.generation_mode.value
        # Convert nested models
        data["documents_generated"] = [d.model_dump() for d in self.documents_generated]
        data["intake_fields"] = [f.model_dump() for f in self.intake_fields]
        return data

    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> "ServiceCatalogueEntry":
        """Create from MongoDB document."""
        # Handle enum conversion
        if "category" in data and isinstance(data["category"], str):
            data["category"] = ServiceCategory(data["category"])
        if "pricing_model" in data and isinstance(data["pricing_model"], str):
            data["pricing_model"] = PricingModel(data["pricing_model"])
        if "delivery_type" in data and isinstance(data["delivery_type"], str):
            data["delivery_type"] = DeliveryType(data["delivery_type"])
        if "generation_mode" in data and isinstance(data["generation_mode"], str):
            data["generation_mode"] = GenerationMode(data["generation_mode"])
        
        # Handle nested models
        if "documents_generated" in data:
            data["documents_generated"] = [
                DocumentDefinition(**d) if isinstance(d, dict) else d 
                for d in data["documents_generated"]
            ]
        if "intake_fields" in data:
            data["intake_fields"] = [
                IntakeFieldSchema(**f) if isinstance(f, dict) else f 
                for f in data["intake_fields"]
            ]
        
        return cls(**data)


# ============================================================================
# SERVICE CATALOGUE SERVICE
# ============================================================================

class ServiceCatalogueService:
    """
    Service for managing the Service Catalogue.
    All service lookups MUST go through this service.
    """
    
    COLLECTION = "service_catalogue"
    
    async def get_service(self, service_code: str) -> Optional[ServiceCatalogueEntry]:
        """
        Get a service by code.
        Returns None if service doesn't exist or is inactive.
        """
        db = database.get_db()
        doc = await db[self.COLLECTION].find_one(
            {"service_code": service_code},
            {"_id": 0}
        )
        if not doc:
            return None
        return ServiceCatalogueEntry.from_dict(doc)
    
    async def get_active_service(self, service_code: str) -> Optional[ServiceCatalogueEntry]:
        """Get a service only if it's active."""
        db = database.get_db()
        doc = await db[self.COLLECTION].find_one(
            {"service_code": service_code, "active": True},
            {"_id": 0}
        )
        if not doc:
            return None
        return ServiceCatalogueEntry.from_dict(doc)
    
    async def list_services(
        self,
        category: Optional[ServiceCategory] = None,
        active_only: bool = True,
        requires_cvp: Optional[bool] = None,
    ) -> List[ServiceCatalogueEntry]:
        """List services with optional filtering."""
        db = database.get_db()
        
        query = {}
        if active_only:
            query["active"] = True
        if category:
            query["category"] = category.value
        if requires_cvp is not None:
            query["requires_cvp_subscription"] = requires_cvp
        
        cursor = db[self.COLLECTION].find(query, {"_id": 0}).sort("display_order", 1)
        docs = await cursor.to_list(length=None)
        
        return [ServiceCatalogueEntry.from_dict(d) for d in docs]
    
    async def list_all_services(self, include_inactive: bool = False) -> List[ServiceCatalogueEntry]:
        """List all services (for admin)."""
        db = database.get_db()
        
        query = {} if include_inactive else {"active": True}
        cursor = db[self.COLLECTION].find(query, {"_id": 0}).sort("display_order", 1)
        docs = await cursor.to_list(length=None)
        
        return [ServiceCatalogueEntry.from_dict(d) for d in docs]
    
    async def create_service(
        self,
        entry: ServiceCatalogueEntry,
        created_by: str,
    ) -> ServiceCatalogueEntry:
        """Create a new service in the catalogue."""
        db = database.get_db()
        
        # Check for duplicate service_code
        existing = await db[self.COLLECTION].find_one({"service_code": entry.service_code})
        if existing:
            raise ValueError(f"Service code already exists: {entry.service_code}")
        
        # Set audit fields
        entry.created_at = datetime.now(timezone.utc)
        entry.updated_at = datetime.now(timezone.utc)
        entry.created_by = created_by
        entry.updated_by = created_by
        
        await db[self.COLLECTION].insert_one(entry.to_dict())
        logger.info(f"Service created: {entry.service_code} by {created_by}")
        
        return entry
    
    async def update_service(
        self,
        service_code: str,
        updates: Dict[str, Any],
        updated_by: str,
    ) -> Optional[ServiceCatalogueEntry]:
        """
        Update a service.
        Note: service_code cannot be changed (immutable).
        """
        db = database.get_db()
        
        # Prevent service_code modification
        if "service_code" in updates:
            del updates["service_code"]
        
        # Set audit field
        updates["updated_at"] = datetime.now(timezone.utc)
        updates["updated_by"] = updated_by
        
        result = await db[self.COLLECTION].update_one(
            {"service_code": service_code},
            {"$set": updates}
        )
        
        if result.modified_count == 0:
            return None
        
        logger.info(f"Service updated: {service_code} by {updated_by}")
        return await self.get_service(service_code)
    
    async def deactivate_service(self, service_code: str, updated_by: str) -> bool:
        """Deactivate a service (soft delete)."""
        db = database.get_db()
        
        result = await db[self.COLLECTION].update_one(
            {"service_code": service_code},
            {
                "$set": {
                    "active": False,
                    "updated_at": datetime.now(timezone.utc),
                    "updated_by": updated_by,
                }
            }
        )
        
        if result.modified_count > 0:
            logger.info(f"Service deactivated: {service_code} by {updated_by}")
            return True
        return False
    
    async def activate_service(self, service_code: str, updated_by: str) -> bool:
        """Activate a service."""
        db = database.get_db()
        
        result = await db[self.COLLECTION].update_one(
            {"service_code": service_code},
            {
                "$set": {
                    "active": True,
                    "updated_at": datetime.now(timezone.utc),
                    "updated_by": updated_by,
                }
            }
        )
        
        if result.modified_count > 0:
            logger.info(f"Service activated: {service_code} by {updated_by}")
            return True
        return False
    
    async def validate_service_for_order(
        self,
        service_code: str,
        user_plan: Optional[str] = None,
        has_cvp_subscription: bool = False,
    ) -> tuple[bool, str]:
        """
        Validate if a service can be ordered.
        Returns (is_valid, error_message).
        """
        service = await self.get_active_service(service_code)
        
        if not service:
            return False, f"Service not found or inactive: {service_code}"
        
        # Check CVP subscription requirement
        if service.requires_cvp_subscription and not has_cvp_subscription:
            return False, f"Service {service_code} requires an active CVP subscription"
        
        # Check plan restrictions
        if service.allowed_plans and user_plan not in service.allowed_plans:
            return False, f"Service {service_code} is not available for plan {user_plan}"
        
        return True, ""
    
    async def get_service_intake_fields(self, service_code: str) -> List[IntakeFieldSchema]:
        """Get intake fields for a service."""
        service = await self.get_service(service_code)
        if not service:
            return []
        return sorted(service.intake_fields, key=lambda f: f.order)
    
    async def get_service_documents(self, service_code: str) -> List[DocumentDefinition]:
        """Get document definitions for a service."""
        service = await self.get_service(service_code)
        if not service:
            return []
        return sorted(service.documents_generated, key=lambda d: d.generation_order)


# Singleton instance
service_catalogue = ServiceCatalogueService()


# ============================================================================
# SEED DATA - Initial services
# ============================================================================

SEED_SERVICES = [
    # CVP Features (included in plans)
    {
        "service_code": "CVP_COMPLIANCE_REPORT",
        "service_name": "Compliance Summary Report",
        "description": "Comprehensive compliance status report for all properties",
        "category": "CVP_FEATURE",
        "pricing_model": "included",
        "price_amount": 0,
        "delivery_type": "portal",
        "documents_generated": [
            {
                "document_code": "COMPLIANCE_SUMMARY",
                "document_name": "Compliance Summary Report",
                "generation_order": 1,
                "review_order": 1,
                "format": "pdf",
                "is_primary": True,
            }
        ],
        "intake_fields": [],
        "review_required": False,
        "generation_mode": "TEMPLATE_ONLY",
        "requires_cvp_subscription": True,
        "active": True,
        "display_order": 1,
    },
    {
        "service_code": "CVP_GAP_ANALYSIS",
        "service_name": "Compliance Gap Analysis",
        "description": "Detailed analysis of compliance gaps and recommended actions",
        "category": "CVP_FEATURE",
        "pricing_model": "included",
        "price_amount": 0,
        "delivery_type": "portal",
        "documents_generated": [
            {
                "document_code": "GAP_ANALYSIS",
                "document_name": "Gap Analysis Report",
                "generation_order": 1,
                "review_order": 1,
                "format": "pdf",
                "is_primary": True,
            }
        ],
        "intake_fields": [],
        "review_required": False,
        "generation_mode": "AI_ASSISTED_JSON",
        "requires_cvp_subscription": True,
        "active": True,
        "display_order": 2,
    },
    
    # CVP Add-ons
    {
        "service_code": "HMO_AUDIT",
        "service_name": "HMO Compliance Audit",
        "description": "Full HMO compliance audit with detailed findings and recommendations",
        "category": "CVP_ADDON",
        "pricing_model": "addon",
        "price_amount": 9900,  # £99
        "delivery_type": "portal+email",
        "documents_generated": [
            {
                "document_code": "HMO_AUDIT_REPORT",
                "document_name": "HMO Audit Report",
                "generation_order": 1,
                "review_order": 1,
                "format": "pdf",
                "is_primary": True,
            }
        ],
        "intake_fields": [
            {"field_id": "property_id", "label": "Property", "field_type": "select", "required": True, "order": 1},
            {"field_id": "hmo_licence_number", "label": "HMO Licence Number", "field_type": "text", "required": False, "order": 2},
            {"field_id": "num_tenants", "label": "Number of Tenants", "field_type": "number", "required": True, "order": 3},
        ],
        "review_required": True,
        "generation_mode": "HYBRID",
        "requires_cvp_subscription": True,
        "active": True,
        "display_order": 10,
    },
    {
        "service_code": "FULL_AUDIT",
        "service_name": "Full Compliance Audit",
        "description": "Comprehensive compliance audit covering all regulatory requirements",
        "category": "CVP_ADDON",
        "pricing_model": "addon",
        "price_amount": 14900,  # £149
        "delivery_type": "portal+email",
        "documents_generated": [
            {
                "document_code": "FULL_AUDIT_REPORT",
                "document_name": "Full Compliance Audit Report",
                "generation_order": 1,
                "review_order": 1,
                "format": "pdf",
                "is_primary": True,
            }
        ],
        "intake_fields": [
            {"field_id": "property_id", "label": "Property", "field_type": "select", "required": True, "order": 1},
        ],
        "review_required": True,
        "generation_mode": "HYBRID",
        "requires_cvp_subscription": True,
        "active": True,
        "display_order": 11,
    },
    {
        "service_code": "MOVE_IN_OUT",
        "service_name": "Move-In/Move-Out Checklist",
        "description": "Professional property inspection checklist for tenant transitions",
        "category": "CVP_ADDON",
        "pricing_model": "addon",
        "price_amount": 4900,  # £49
        "delivery_type": "portal+email",
        "documents_generated": [
            {
                "document_code": "MOVE_CHECKLIST",
                "document_name": "Move-In/Move-Out Checklist",
                "generation_order": 1,
                "review_order": 1,
                "format": "pdf",
                "is_primary": True,
            }
        ],
        "intake_fields": [
            {"field_id": "property_id", "label": "Property", "field_type": "select", "required": True, "order": 1},
            {"field_id": "checklist_type", "label": "Checklist Type", "field_type": "select", "required": True, "options": ["Move-In", "Move-Out"], "order": 2},
            {"field_id": "inspection_date", "label": "Inspection Date", "field_type": "date", "required": True, "order": 3},
        ],
        "review_required": True,
        "generation_mode": "TEMPLATE_ONLY",
        "requires_cvp_subscription": False,
        "active": True,
        "display_order": 12,
    },
    
    # Document Packs (Standalone)
    {
        "service_code": "DOC_PACK_ESSENTIAL",
        "service_name": "Essential Landlord Document Pack",
        "description": "Core landlord documents including tenancy agreement template and notices",
        "category": "DOCUMENT_PACK",
        "pricing_model": "one_time",
        "price_amount": 4999,  # £49.99
        "delivery_type": "portal+email",
        "delivery_format": "zip_bundle",
        "documents_generated": [
            {"document_code": "AST_TEMPLATE", "document_name": "Assured Shorthold Tenancy Agreement", "generation_order": 1, "review_order": 1, "format": "docx", "is_primary": True},
            {"document_code": "DEPOSIT_PRESCRIBED_INFO", "document_name": "Deposit Prescribed Information", "generation_order": 2, "review_order": 2, "format": "docx", "is_primary": False},
            {"document_code": "HOW_TO_RENT_GUIDE", "document_name": "How to Rent Guide", "generation_order": 3, "review_order": 3, "format": "pdf", "is_primary": False},
        ],
        "intake_fields": [
            {"field_id": "landlord_name", "label": "Landlord Full Name", "field_type": "text", "required": True, "order": 1},
            {"field_id": "landlord_address", "label": "Landlord Address", "field_type": "address", "required": True, "order": 2},
            {"field_id": "property_address", "label": "Property Address", "field_type": "address", "required": True, "order": 3},
        ],
        "review_required": True,
        "generation_mode": "TEMPLATE_ONLY",
        "requires_cvp_subscription": False,
        "active": True,
        "display_order": 20,
    },
    {
        "service_code": "DOC_PACK_TENANCY",
        "service_name": "Tenancy Legal & Notices Pack",
        "description": "Complete Section 21 and Section 8 notice pack with supporting documents",
        "category": "DOCUMENT_PACK",
        "pricing_model": "one_time",
        "price_amount": 7999,  # £79.99
        "delivery_type": "portal+email",
        "delivery_format": "zip_bundle",
        "documents_generated": [
            {"document_code": "SECTION_21_NOTICE", "document_name": "Section 21 Notice", "generation_order": 1, "review_order": 1, "format": "pdf", "is_primary": True},
            {"document_code": "SECTION_8_NOTICE", "document_name": "Section 8 Notice", "generation_order": 2, "review_order": 2, "format": "pdf", "is_primary": False},
            {"document_code": "COVER_LETTER", "document_name": "Cover Letter", "generation_order": 3, "review_order": 3, "format": "docx", "is_primary": False},
            {"document_code": "PROOF_OF_SERVICE", "document_name": "Proof of Service Form", "generation_order": 4, "review_order": 4, "format": "pdf", "is_primary": False},
        ],
        "intake_fields": [
            {"field_id": "landlord_name", "label": "Landlord Full Name", "field_type": "text", "required": True, "order": 1},
            {"field_id": "landlord_address", "label": "Landlord Address", "field_type": "address", "required": True, "order": 2},
            {"field_id": "property_address", "label": "Property Address", "field_type": "address", "required": True, "order": 3},
            {"field_id": "tenant_names", "label": "Tenant Name(s)", "field_type": "text", "required": True, "order": 4},
            {"field_id": "tenancy_start_date", "label": "Tenancy Start Date", "field_type": "date", "required": True, "order": 5},
            {"field_id": "grounds", "label": "Grounds for Possession", "field_type": "multi_select", "required": False, "options": ["Ground 8", "Ground 10", "Ground 11"], "order": 6},
        ],
        "review_required": True,
        "generation_mode": "HYBRID",
        "requires_cvp_subscription": False,
        "active": True,
        "display_order": 21,
    },
    {
        "service_code": "DOC_PACK_ULTIMATE",
        "service_name": "Ultimate Landlord Document Pack",
        "description": "Complete landlord document suite including all legal notices, agreements, and compliance documents",
        "category": "DOCUMENT_PACK",
        "pricing_model": "one_time",
        "price_amount": 14999,  # £149.99
        "delivery_type": "portal+email",
        "delivery_format": "zip_bundle",
        "documents_generated": [
            {"document_code": "AST_TEMPLATE", "document_name": "Assured Shorthold Tenancy Agreement", "generation_order": 1, "review_order": 1, "format": "docx", "is_primary": True},
            {"document_code": "SECTION_21_NOTICE", "document_name": "Section 21 Notice", "generation_order": 2, "review_order": 2, "format": "pdf", "is_primary": False},
            {"document_code": "SECTION_8_NOTICE", "document_name": "Section 8 Notice", "generation_order": 3, "review_order": 3, "format": "pdf", "is_primary": False},
            {"document_code": "INVENTORY_TEMPLATE", "document_name": "Property Inventory Template", "generation_order": 4, "review_order": 4, "format": "docx", "is_primary": False},
            {"document_code": "DEPOSIT_PRESCRIBED_INFO", "document_name": "Deposit Prescribed Information", "generation_order": 5, "review_order": 5, "format": "docx", "is_primary": False},
            {"document_code": "RENT_ARREARS_LETTER", "document_name": "Rent Arrears Letter", "generation_order": 6, "review_order": 6, "format": "docx", "is_primary": False},
            {"document_code": "INSPECTION_NOTICE", "document_name": "Property Inspection Notice", "generation_order": 7, "review_order": 7, "format": "docx", "is_primary": False},
        ],
        "intake_fields": [
            {"field_id": "landlord_name", "label": "Landlord Full Name", "field_type": "text", "required": True, "order": 1},
            {"field_id": "landlord_address", "label": "Landlord Address", "field_type": "address", "required": True, "order": 2},
            {"field_id": "property_address", "label": "Property Address", "field_type": "address", "required": True, "order": 3},
            {"field_id": "tenant_names", "label": "Tenant Name(s)", "field_type": "text", "required": True, "order": 4},
            {"field_id": "tenancy_start_date", "label": "Tenancy Start Date", "field_type": "date", "required": True, "order": 5},
            {"field_id": "monthly_rent", "label": "Monthly Rent (£)", "field_type": "number", "required": True, "order": 6},
            {"field_id": "deposit_amount", "label": "Deposit Amount (£)", "field_type": "number", "required": True, "order": 7},
        ],
        "review_required": True,
        "generation_mode": "HYBRID",
        "requires_cvp_subscription": False,
        "active": True,
        "display_order": 22,
    },
    
    # Standalone Reports - Automation
    {
        "service_code": "AI_WF_BLUEPRINT",
        "service_name": "Workflow Automation Blueprint",
        "description": "AI-powered analysis of your business processes with automation recommendations",
        "category": "STANDALONE_REPORT",
        "pricing_model": "one_time",
        "price_amount": 29900,  # £299
        "delivery_type": "portal+email",
        "documents_generated": [
            {"document_code": "WORKFLOW_BLUEPRINT", "document_name": "Workflow Automation Blueprint", "generation_order": 1, "review_order": 1, "format": "pdf", "is_primary": True},
        ],
        "intake_fields": [
            {"field_id": "business_name", "label": "Business Name", "field_type": "text", "required": True, "order": 1},
            {"field_id": "industry", "label": "Industry", "field_type": "select", "required": True, "options": ["Property Management", "Real Estate", "Legal Services", "Other"], "order": 2},
            {"field_id": "current_processes", "label": "Current Key Processes", "field_type": "textarea", "required": True, "order": 3},
            {"field_id": "pain_points", "label": "Pain Points / Bottlenecks", "field_type": "textarea", "required": True, "order": 4},
        ],
        "review_required": True,
        "generation_mode": "AI_ASSISTED_JSON",
        "requires_cvp_subscription": False,
        "active": True,
        "display_order": 30,
    },
    {
        "service_code": "AI_PROC_MAP",
        "service_name": "Business Process Mapping",
        "description": "Visual mapping of your business processes with optimization recommendations",
        "category": "STANDALONE_REPORT",
        "pricing_model": "one_time",
        "price_amount": 19900,  # £199
        "delivery_type": "portal+email",
        "documents_generated": [
            {"document_code": "PROCESS_MAP", "document_name": "Business Process Map", "generation_order": 1, "review_order": 1, "format": "pdf", "is_primary": True},
        ],
        "intake_fields": [
            {"field_id": "business_name", "label": "Business Name", "field_type": "text", "required": True, "order": 1},
            {"field_id": "process_name", "label": "Process to Map", "field_type": "text", "required": True, "order": 2},
            {"field_id": "process_description", "label": "Process Description", "field_type": "textarea", "required": True, "order": 3},
        ],
        "review_required": True,
        "generation_mode": "AI_ASSISTED_JSON",
        "requires_cvp_subscription": False,
        "active": True,
        "display_order": 31,
    },
    {
        "service_code": "AI_TOOL_REC",
        "service_name": "AI Tool Recommendation Report",
        "description": "Personalized AI tool recommendations based on your business needs",
        "category": "STANDALONE_REPORT",
        "pricing_model": "one_time",
        "price_amount": 14900,  # £149
        "delivery_type": "portal+email",
        "documents_generated": [
            {"document_code": "TOOL_RECOMMENDATIONS", "document_name": "AI Tool Recommendations", "generation_order": 1, "review_order": 1, "format": "pdf", "is_primary": True},
        ],
        "intake_fields": [
            {"field_id": "business_name", "label": "Business Name", "field_type": "text", "required": True, "order": 1},
            {"field_id": "business_goals", "label": "Business Goals", "field_type": "textarea", "required": True, "order": 2},
            {"field_id": "current_tools", "label": "Current Tools in Use", "field_type": "textarea", "required": False, "order": 3},
            {"field_id": "budget_range", "label": "Monthly Budget Range", "field_type": "select", "required": True, "options": ["Under £100", "£100-500", "£500-1000", "£1000+"], "order": 4},
        ],
        "review_required": True,
        "generation_mode": "AI_ASSISTED_JSON",
        "requires_cvp_subscription": False,
        "active": True,
        "display_order": 32,
    },
    
    # Standalone Reports - Market Research
    {
        "service_code": "MR_BASIC",
        "service_name": "Market Research Report - Basic",
        "description": "Basic market analysis for a specific area including rental yields and trends",
        "category": "STANDALONE_REPORT",
        "pricing_model": "one_time",
        "price_amount": 9900,  # £99
        "delivery_type": "portal+email",
        "documents_generated": [
            {"document_code": "MARKET_RESEARCH_BASIC", "document_name": "Market Research Report", "generation_order": 1, "review_order": 1, "format": "pdf", "is_primary": True},
        ],
        "intake_fields": [
            {"field_id": "location", "label": "Target Location", "field_type": "address", "required": True, "order": 1},
            {"field_id": "property_type", "label": "Property Type", "field_type": "select", "required": True, "options": ["Flat", "House", "HMO", "Commercial"], "order": 2},
            {"field_id": "bedrooms", "label": "Number of Bedrooms", "field_type": "number", "required": False, "order": 3},
        ],
        "review_required": True,
        "generation_mode": "AI_ASSISTED_JSON",
        "requires_cvp_subscription": False,
        "active": True,
        "display_order": 40,
    },
    {
        "service_code": "MR_ADV",
        "service_name": "Market Research Report - Advanced",
        "description": "Comprehensive market analysis with competitor analysis, demand forecasting, and investment recommendations",
        "category": "STANDALONE_REPORT",
        "pricing_model": "one_time",
        "price_amount": 24900,  # £249
        "delivery_type": "portal+email",
        "documents_generated": [
            {"document_code": "MARKET_RESEARCH_ADV", "document_name": "Advanced Market Research Report", "generation_order": 1, "review_order": 1, "format": "pdf", "is_primary": True},
            {"document_code": "COMPETITOR_ANALYSIS", "document_name": "Competitor Analysis", "generation_order": 2, "review_order": 2, "format": "pdf", "is_primary": False},
        ],
        "intake_fields": [
            {"field_id": "location", "label": "Target Location", "field_type": "address", "required": True, "order": 1},
            {"field_id": "property_type", "label": "Property Type", "field_type": "select", "required": True, "options": ["Flat", "House", "HMO", "Commercial"], "order": 2},
            {"field_id": "investment_budget", "label": "Investment Budget", "field_type": "select", "required": True, "options": ["Under £100k", "£100k-250k", "£250k-500k", "£500k+"], "order": 3},
            {"field_id": "investment_goals", "label": "Investment Goals", "field_type": "textarea", "required": True, "order": 4},
        ],
        "review_required": True,
        "generation_mode": "AI_ASSISTED_JSON",
        "requires_cvp_subscription": False,
        "active": True,
        "display_order": 41,
    },
    
    # Property Services - Active Only
    {
        "service_code": "DUE_DILIGENCE",
        "service_name": "Investment Due Diligence Report",
        "description": "Comprehensive due diligence for property investors covering legal, financial, and compliance aspects",
        "category": "STANDALONE_REPORT",
        "pricing_model": "one_time",
        "price_amount": 49900,  # £499
        "delivery_type": "portal+email",
        "documents_generated": [
            {"document_code": "DUE_DILIGENCE_MAIN", "document_name": "Due Diligence Report", "generation_order": 1, "review_order": 1, "format": "pdf", "is_primary": True},
            {"document_code": "FINANCIAL_ANALYSIS", "document_name": "Financial Analysis Summary", "generation_order": 2, "review_order": 2, "format": "pdf", "is_primary": False},
            {"document_code": "RISK_ASSESSMENT", "document_name": "Risk Assessment Matrix", "generation_order": 3, "review_order": 3, "format": "pdf", "is_primary": False},
        ],
        "intake_fields": [
            {"field_id": "property_address", "label": "Property Address", "field_type": "address", "required": True, "order": 1},
            {"field_id": "asking_price", "label": "Asking Price (£)", "field_type": "number", "required": True, "order": 2},
            {"field_id": "property_type", "label": "Property Type", "field_type": "select", "required": True, "options": ["Residential BTL", "HMO", "Commercial", "Mixed Use", "Development"], "order": 3},
            {"field_id": "investment_strategy", "label": "Investment Strategy", "field_type": "select", "required": True, "options": ["Buy-to-Let", "Flip", "BRRR", "Development", "Commercial Let"], "order": 4},
            {"field_id": "financing_method", "label": "Financing Method", "field_type": "select", "required": True, "options": ["Cash Purchase", "BTL Mortgage", "Bridging Finance", "Commercial Mortgage"], "order": 5},
            {"field_id": "specific_concerns", "label": "Specific Concerns or Questions", "field_type": "textarea", "required": False, "order": 6},
        ],
        "review_required": True,
        "generation_mode": "AI_ASSISTED_JSON",
        "requires_cvp_subscription": False,
        "active": True,
        "display_order": 43,
    },
    {
        "service_code": "RENT_REVIEW",
        "service_name": "Rent Review Analysis",
        "description": "Market-based rent review analysis with comparable evidence and recommended rental value",
        "category": "STANDALONE_REPORT",
        "pricing_model": "one_time",
        "price_amount": 7900,  # £79
        "delivery_type": "portal+email",
        "documents_generated": [
            {"document_code": "RENT_REVIEW_REPORT", "document_name": "Rent Review Analysis Report", "generation_order": 1, "review_order": 1, "format": "pdf", "is_primary": True},
        ],
        "intake_fields": [
            {"field_id": "property_address", "label": "Property Address", "field_type": "address", "required": True, "order": 1},
            {"field_id": "current_rent", "label": "Current Monthly Rent (£)", "field_type": "number", "required": True, "order": 2},
            {"field_id": "last_review_date", "label": "Last Rent Review Date", "field_type": "date", "required": False, "order": 3},
            {"field_id": "property_type", "label": "Property Type", "field_type": "select", "required": True, "options": ["Flat", "House", "HMO Room", "Studio"], "order": 4},
            {"field_id": "bedrooms", "label": "Number of Bedrooms", "field_type": "number", "required": True, "order": 5},
            {"field_id": "recent_improvements", "label": "Recent Property Improvements", "field_type": "textarea", "required": False, "order": 6},
        ],
        "review_required": True,
        "generation_mode": "AI_ASSISTED_JSON",
        "requires_cvp_subscription": False,
        "active": True,
        "display_order": 44,
    },
    {
        "service_code": "TENANT_REF",
        "service_name": "Tenant Referencing Report",
        "description": "Comprehensive tenant background check including credit, employment, and landlord references",
        "category": "STANDALONE_REPORT",
        "pricing_model": "one_time",
        "price_amount": 3500,  # £35
        "delivery_type": "portal+email",
        "documents_generated": [
            {"document_code": "TENANT_REF_REPORT", "document_name": "Tenant Reference Report", "generation_order": 1, "review_order": 1, "format": "pdf", "is_primary": True},
        ],
        "intake_fields": [
            {"field_id": "tenant_name", "label": "Applicant Full Name", "field_type": "text", "required": True, "order": 1},
            {"field_id": "tenant_email", "label": "Applicant Email", "field_type": "text", "required": True, "order": 2},
            {"field_id": "tenant_phone", "label": "Applicant Phone", "field_type": "text", "required": True, "order": 3},
            {"field_id": "current_address", "label": "Current Address", "field_type": "address", "required": True, "order": 4},
            {"field_id": "proposed_rent", "label": "Proposed Monthly Rent (£)", "field_type": "number", "required": True, "order": 5},
            {"field_id": "employment_status", "label": "Employment Status", "field_type": "select", "required": True, "options": ["Employed", "Self-Employed", "Student", "Retired", "Unemployed"], "order": 6},
        ],
        "review_required": True,
        "generation_mode": "TEMPLATE_ONLY",
        "requires_cvp_subscription": False,
        "active": True,
        "display_order": 45,
    },
    {
        "service_code": "EPC_CONSULT",
        "service_name": "Energy Performance Consultation",
        "description": "Expert analysis of your EPC with prioritized improvement recommendations and cost estimates",
        "category": "STANDALONE_REPORT",
        "pricing_model": "one_time",
        "price_amount": 9900,  # £99
        "delivery_type": "portal+email",
        "documents_generated": [
            {"document_code": "EPC_CONSULTATION", "document_name": "EPC Improvement Consultation", "generation_order": 1, "review_order": 1, "format": "pdf", "is_primary": True},
        ],
        "intake_fields": [
            {"field_id": "property_address", "label": "Property Address", "field_type": "address", "required": True, "order": 1},
            {"field_id": "current_epc_rating", "label": "Current EPC Rating", "field_type": "select", "required": True, "options": ["A", "B", "C", "D", "E", "F", "G", "Unknown"], "order": 2},
            {"field_id": "target_rating", "label": "Target EPC Rating", "field_type": "select", "required": True, "options": ["A", "B", "C", "D", "E"], "order": 3},
            {"field_id": "property_type", "label": "Property Type", "field_type": "select", "required": True, "options": ["Flat", "Terraced", "Semi-Detached", "Detached", "Bungalow"], "order": 4},
            {"field_id": "heating_type", "label": "Current Heating Type", "field_type": "select", "required": True, "options": ["Gas Boiler", "Electric Storage", "Oil Boiler", "Heat Pump", "Other"], "order": 5},
            {"field_id": "improvement_budget", "label": "Budget for Improvements", "field_type": "select", "required": True, "options": ["Under £5k", "£5k-10k", "£10k-20k", "£20k+", "Flexible"], "order": 6},
        ],
        "review_required": True,
        "generation_mode": "AI_ASSISTED_JSON",
        "requires_cvp_subscription": False,
        "active": True,
        "display_order": 46,
    },
    {
        "service_code": "HMO_LICENCE_SUPPORT",
        "service_name": "HMO Licensing Support Pack",
        "description": "Complete HMO licence application support including documentation and compliance checklist",
        "category": "STANDALONE_REPORT",
        "pricing_model": "one_time",
        "price_amount": 29900,  # £299
        "delivery_type": "portal+email",
        "documents_generated": [
            {"document_code": "HMO_APPLICATION_GUIDE", "document_name": "HMO Application Guide", "generation_order": 1, "review_order": 1, "format": "pdf", "is_primary": True},
            {"document_code": "HMO_COMPLIANCE_CHECKLIST", "document_name": "HMO Compliance Checklist", "generation_order": 2, "review_order": 2, "format": "pdf", "is_primary": False},
            {"document_code": "FIRE_SAFETY_PLAN", "document_name": "Fire Safety Plan Template", "generation_order": 3, "review_order": 3, "format": "docx", "is_primary": False},
        ],
        "intake_fields": [
            {"field_id": "property_address", "label": "Property Address", "field_type": "address", "required": True, "order": 1},
            {"field_id": "local_authority", "label": "Local Authority", "field_type": "text", "required": True, "order": 2},
            {"field_id": "num_storeys", "label": "Number of Storeys", "field_type": "number", "required": True, "order": 3},
            {"field_id": "num_lettable_rooms", "label": "Number of Lettable Rooms", "field_type": "number", "required": True, "order": 4},
            {"field_id": "max_occupants", "label": "Maximum Number of Occupants", "field_type": "number", "required": True, "order": 5},
            {"field_id": "licence_type", "label": "Licence Type Required", "field_type": "select", "required": True, "options": ["Mandatory HMO", "Additional HMO", "Selective", "Unknown"], "order": 6},
        ],
        "review_required": True,
        "generation_mode": "HYBRID",
        "requires_cvp_subscription": False,
        "active": True,
        "display_order": 47,
    },
    {
        "service_code": "PORTFOLIO_ANALYSIS",
        "service_name": "Portfolio Performance Analysis",
        "description": "Comprehensive analysis of your property portfolio with ROI calculations and optimization recommendations",
        "category": "STANDALONE_REPORT",
        "pricing_model": "one_time",
        "price_amount": 39900,  # £399
        "delivery_type": "portal+email",
        "documents_generated": [
            {"document_code": "PORTFOLIO_REPORT", "document_name": "Portfolio Performance Report", "generation_order": 1, "review_order": 1, "format": "pdf", "is_primary": True},
            {"document_code": "PROPERTY_COMPARISON", "document_name": "Property-by-Property Comparison", "generation_order": 2, "review_order": 2, "format": "pdf", "is_primary": False},
            {"document_code": "OPTIMIZATION_PLAN", "document_name": "Portfolio Optimization Plan", "generation_order": 3, "review_order": 3, "format": "pdf", "is_primary": False},
        ],
        "intake_fields": [
            {"field_id": "num_properties", "label": "Number of Properties", "field_type": "number", "required": True, "order": 1},
            {"field_id": "property_details", "label": "Property Details (Address, Type, Current Rent)", "field_type": "textarea", "required": True, "help_text": "List each property with address, type and monthly rent", "order": 2},
            {"field_id": "total_investment", "label": "Total Portfolio Investment (£)", "field_type": "number", "required": True, "order": 3},
            {"field_id": "total_debt", "label": "Total Mortgage/Debt Outstanding (£)", "field_type": "number", "required": False, "order": 4},
            {"field_id": "investment_goals", "label": "Investment Goals", "field_type": "select", "required": True, "options": ["Maximize Cash Flow", "Capital Growth", "Balanced", "Exit Strategy"], "order": 5},
            {"field_id": "time_horizon", "label": "Investment Time Horizon", "field_type": "select", "required": True, "options": ["1-3 years", "3-5 years", "5-10 years", "10+ years"], "order": 6},
        ],
        "review_required": True,
        "generation_mode": "AI_ASSISTED_JSON",
        "requires_cvp_subscription": False,
        "active": True,
        "display_order": 48,
    },
    {
        "service_code": "LEASE_EXTENSION",
        "service_name": "Lease Extension Valuation",
        "description": "Professional lease extension valuation with marriage value calculation and negotiation guidance",
        "category": "STANDALONE_REPORT",
        "pricing_model": "one_time",
        "price_amount": 24900,  # £249
        "delivery_type": "portal+email",
        "documents_generated": [
            {"document_code": "LEASE_VALUATION", "document_name": "Lease Extension Valuation Report", "generation_order": 1, "review_order": 1, "format": "pdf", "is_primary": True},
            {"document_code": "NEGOTIATION_GUIDE", "document_name": "Negotiation Strategy Guide", "generation_order": 2, "review_order": 2, "format": "pdf", "is_primary": False},
        ],
        "intake_fields": [
            {"field_id": "property_address", "label": "Property Address", "field_type": "address", "required": True, "order": 1},
            {"field_id": "current_lease_years", "label": "Current Lease Length (Years)", "field_type": "number", "required": True, "order": 2},
            {"field_id": "ground_rent", "label": "Current Ground Rent (£/year)", "field_type": "number", "required": True, "order": 3},
            {"field_id": "estimated_value", "label": "Estimated Property Value (£)", "field_type": "number", "required": True, "order": 4},
            {"field_id": "target_extension", "label": "Target Extension Length", "field_type": "select", "required": True, "options": ["90 years", "125 years", "990 years", "Other"], "order": 5},
        ],
        "review_required": True,
        "generation_mode": "AI_ASSISTED_JSON",
        "requires_cvp_subscription": False,
        "active": True,
        "display_order": 49,
    },
    {
        "service_code": "AIRBNB_SETUP",
        "service_name": "Short-Let Setup Consultation",
        "description": "Complete guide to setting up your property for Airbnb/short-let including pricing strategy and compliance",
        "category": "STANDALONE_REPORT",
        "pricing_model": "one_time",
        "price_amount": 19900,  # £199
        "delivery_type": "portal+email",
        "documents_generated": [
            {"document_code": "SHORTLET_GUIDE", "document_name": "Short-Let Setup Guide", "generation_order": 1, "review_order": 1, "format": "pdf", "is_primary": True},
            {"document_code": "PRICING_STRATEGY", "document_name": "Pricing Strategy Report", "generation_order": 2, "review_order": 2, "format": "pdf", "is_primary": False},
            {"document_code": "COMPLIANCE_CHECKLIST", "document_name": "Short-Let Compliance Checklist", "generation_order": 3, "review_order": 3, "format": "pdf", "is_primary": False},
        ],
        "intake_fields": [
            {"field_id": "property_address", "label": "Property Address", "field_type": "address", "required": True, "order": 1},
            {"field_id": "property_type", "label": "Property Type", "field_type": "select", "required": True, "options": ["Entire Property", "Room Only", "Annexe/Outbuilding"], "order": 2},
            {"field_id": "bedrooms", "label": "Number of Bedrooms", "field_type": "number", "required": True, "order": 3},
            {"field_id": "target_platform", "label": "Target Platform", "field_type": "multi_select", "required": True, "options": ["Airbnb", "Booking.com", "VRBO", "Direct Bookings"], "order": 4},
            {"field_id": "location_type", "label": "Location Type", "field_type": "select", "required": True, "options": ["City Centre", "Suburban", "Rural", "Coastal/Tourist"], "order": 5},
            {"field_id": "current_furnishing", "label": "Current Furnishing Level", "field_type": "select", "required": True, "options": ["Unfurnished", "Part-Furnished", "Fully Furnished", "Holiday-Ready"], "order": 6},
        ],
        "review_required": True,
        "generation_mode": "AI_ASSISTED_JSON",
        "requires_cvp_subscription": False,
        "active": True,
        "display_order": 50,
    },
]


async def seed_service_catalogue():
    """Seed the service catalogue with initial services."""
    db = database.get_db()
    
    for service_data in SEED_SERVICES:
        existing = await db[ServiceCatalogueService.COLLECTION].find_one(
            {"service_code": service_data["service_code"]}
        )
        
        if not existing:
            service_data["created_at"] = datetime.now(timezone.utc)
            service_data["updated_at"] = datetime.now(timezone.utc)
            service_data["created_by"] = "system"
            service_data["updated_by"] = "system"
            
            await db[ServiceCatalogueService.COLLECTION].insert_one(service_data)
            logger.info(f"Seeded service: {service_data['service_code']}")
        else:
            logger.debug(f"Service already exists: {service_data['service_code']}")
    
    # Create index on service_code
    await db[ServiceCatalogueService.COLLECTION].create_index("service_code", unique=True)
    logger.info("Service catalogue seeding complete")
