"""Operational subscription event types (business events, not raw Stripe mirrors)."""
from __future__ import annotations

from typing import Dict, Tuple

SUBSCRIPTION_RENEWED = "SUBSCRIPTION_RENEWED"
SUBSCRIPTION_RENEWAL_FAILED = "SUBSCRIPTION_RENEWAL_FAILED"
SUBSCRIPTION_CANCELLED = "SUBSCRIPTION_CANCELLED"
SUBSCRIPTION_REACTIVATED = "SUBSCRIPTION_REACTIVATED"
SUBSCRIPTION_UPGRADED = "SUBSCRIPTION_UPGRADED"
SUBSCRIPTION_DOWNGRADED = "SUBSCRIPTION_DOWNGRADED"
TRIAL_CONVERTED = "TRIAL_CONVERTED"
REFUND_ISSUED = "REFUND_ISSUED"
CHARGEBACK_RECEIVED = "CHARGEBACK_RECEIVED"
PAYMENT_RECONCILIATION_MISMATCH = "PAYMENT_RECONCILIATION_MISMATCH"

OPERATIONAL_EVENT_LABELS: Dict[str, str] = {
    SUBSCRIPTION_RENEWED: "Subscription renewed successfully",
    SUBSCRIPTION_RENEWAL_FAILED: "Subscription renewal payment failed",
    SUBSCRIPTION_CANCELLED: "Subscription cancelled",
    SUBSCRIPTION_REACTIVATED: "Subscription reactivated",
    SUBSCRIPTION_UPGRADED: "Subscription upgraded",
    SUBSCRIPTION_DOWNGRADED: "Subscription downgraded",
    TRIAL_CONVERTED: "Trial converted to paid subscription",
    REFUND_ISSUED: "Refund issued",
    CHARGEBACK_RECEIVED: "Chargeback received",
    PAYMENT_RECONCILIATION_MISMATCH: "Payment received but reconciliation pending",
}

OPERATIONAL_EVENT_SEVERITY: Dict[str, str] = {
    SUBSCRIPTION_RENEWED: "info",
    SUBSCRIPTION_RENEWAL_FAILED: "high",
    SUBSCRIPTION_CANCELLED: "high",
    SUBSCRIPTION_REACTIVATED: "info",
    SUBSCRIPTION_UPGRADED: "info",
    SUBSCRIPTION_DOWNGRADED: "medium",
    TRIAL_CONVERTED: "info",
    REFUND_ISSUED: "high",
    CHARGEBACK_RECEIVED: "critical",
    PAYMENT_RECONCILIATION_MISMATCH: "high",
}

IMMEDIATE_EMAIL_EVENT_TYPES = frozenset(
    {
        SUBSCRIPTION_RENEWAL_FAILED,
        SUBSCRIPTION_CANCELLED,
        REFUND_ISSUED,
        CHARGEBACK_RECEIVED,
        PAYMENT_RECONCILIATION_MISMATCH,
    }
)
