"""Pricing workflow enums for work orders (MongoDB string fields)."""

PRICING_MODE_COMPLIANCE_FIXED_QUOTE = "COMPLIANCE_FIXED_QUOTE"
PRICING_MODE_MAINTENANCE_PREQUOTE = "MAINTENANCE_PREQUOTE"
PRICING_MODE_MAINTENANCE_INSPECTION_REQUIRED = "MAINTENANCE_INSPECTION_REQUIRED"

ALLOWED_PRICING_MODES = frozenset(
    {
        PRICING_MODE_COMPLIANCE_FIXED_QUOTE,
        PRICING_MODE_MAINTENANCE_PREQUOTE,
        PRICING_MODE_MAINTENANCE_INSPECTION_REQUIRED,
    }
)

PRICE_STATUS_AWAITING_QUOTE = "AWAITING_QUOTE"
PRICE_STATUS_QUOTED = "QUOTED"
PRICE_STATUS_APPROVED = "APPROVED"
PRICE_STATUS_REJECTED = "REJECTED"
PRICE_STATUS_DISPUTED = "DISPUTED"

ALLOWED_PRICE_STATUSES = frozenset(
    {
        PRICE_STATUS_AWAITING_QUOTE,
        PRICE_STATUS_QUOTED,
        PRICE_STATUS_APPROVED,
        PRICE_STATUS_REJECTED,
        PRICE_STATUS_DISPUTED,
    }
)

DEFAULT_PRICE_CURRENCY = "GBP"
