"""Work order visit scheduling lifecycle (not a calendar engine — explicit propose / confirm / reschedule / cancel)."""

SCHEDULE_STATUS_PROPOSED = "proposed"
SCHEDULE_STATUS_CONFIRMED = "confirmed"
SCHEDULE_STATUS_RESCHEDULE_REQUESTED = "reschedule_requested"
SCHEDULE_STATUS_COMPLETED = "completed"
SCHEDULE_STATUS_CANCELLED = "cancelled"

SCHEDULE_ACTOR_CLIENT = "client"
SCHEDULE_ACTOR_CONTRACTOR = "contractor"
SCHEDULE_ACTOR_ADMIN = "admin"

ALLOWED_SCHEDULE_STATUSES = frozenset(
    {
        SCHEDULE_STATUS_PROPOSED,
        SCHEDULE_STATUS_CONFIRMED,
        SCHEDULE_STATUS_RESCHEDULE_REQUESTED,
        SCHEDULE_STATUS_COMPLETED,
        SCHEDULE_STATUS_CANCELLED,
    }
)

# Audit / notification metadata (string event_type for cross-system logs)
AUDIT_EVENT_SCHEDULE_PROPOSED = "SCHEDULE_PROPOSED"
AUDIT_EVENT_SCHEDULE_CONFIRMED = "SCHEDULE_CONFIRMED"
AUDIT_EVENT_SCHEDULE_RESCHEDULE_REQUESTED = "SCHEDULE_RESCHEDULE_REQUESTED"
AUDIT_EVENT_SCHEDULE_CANCELLED = "SCHEDULE_CANCELLED"
AUDIT_EVENT_SCHEDULE_REMINDER = "SCHEDULE_REMINDER_SENT"
