"""Work order contractor assignment routing states (client confirmation flow)."""

ASSIGNMENT_ROUTING_UNASSIGNED = "UNASSIGNED"
ASSIGNMENT_ROUTING_CONTRACTOR_RECOMMENDED = "CONTRACTOR_RECOMMENDED"
ASSIGNMENT_ROUTING_PENDING_CLIENT_CONFIRMATION = "PENDING_CLIENT_CONFIRMATION"
ASSIGNMENT_ROUTING_CONTRACTOR_DECLINED = "CONTRACTOR_DECLINED"
ASSIGNMENT_ROUTING_ESCALATED_TO_ADMIN = "ESCALATED_TO_ADMIN"
ASSIGNMENT_ROUTING_ASSIGNED = "ASSIGNED"

PENDING_STATES = frozenset(
    {
        ASSIGNMENT_ROUTING_PENDING_CLIENT_CONFIRMATION,
        ASSIGNMENT_ROUTING_CONTRACTOR_DECLINED,
    }
)
