"""Work order execution kind and compliance execution metadata (separate from maintenance repair semantics)."""

WORK_ORDER_KIND_MAINTENANCE = "MAINTENANCE"
WORK_ORDER_KIND_COMPLIANCE = "COMPLIANCE"

# Contractor execution surface (stored on contractor.execution_capabilities)
EXECUTION_CAPABILITY_MAINTENANCE = "maintenance"
EXECUTION_CAPABILITY_COMPLIANCE = "compliance"
EXECUTION_CAPABILITY_BOTH = "both"
ALLOWED_EXECUTION_CAPABILITIES = frozenset(
    {EXECUTION_CAPABILITY_MAINTENANCE, EXECUTION_CAPABILITY_COMPLIANCE, EXECUTION_CAPABILITY_BOTH}
)

# Purpose of a compliance execution work order (inspection / renewal / certification / remedial)
COMPLIANCE_PURPOSE_INSPECTION = "inspection"
COMPLIANCE_PURPOSE_RENEWAL = "renewal"
COMPLIANCE_PURPOSE_CERTIFICATION = "certification"
COMPLIANCE_PURPOSE_REMEDIAL = "remedial"
ALLOWED_COMPLIANCE_PURPOSES = frozenset(
    {
        COMPLIANCE_PURPOSE_INSPECTION,
        COMPLIANCE_PURPOSE_RENEWAL,
        COMPLIANCE_PURPOSE_CERTIFICATION,
        COMPLIANCE_PURPOSE_REMEDIAL,
    }
)

# How the compliance work order was initiated
COMPLIANCE_GENERATED_FROM_REQUIREMENT = "requirement"
COMPLIANCE_GENERATED_FROM_RISK_SIGNAL = "risk_signal"
COMPLIANCE_GENERATED_FROM_MANUAL = "manual"
ALLOWED_COMPLIANCE_GENERATED_FROM = frozenset(
    {
        COMPLIANCE_GENERATED_FROM_REQUIREMENT,
        COMPLIANCE_GENERATED_FROM_RISK_SIGNAL,
        COMPLIANCE_GENERATED_FROM_MANUAL,
    }
)

# Maintenance work order category when kind is MAINTENANCE (existing); compliance jobs use category COMPLIANCE_BUCKET
WORK_ORDER_CATEGORY_COMPLIANCE = "compliance"

# --- Compliance execution booking / proof (COMPLIANCE work orders only; orthogonal to assignment_routing_state) ---
COMPLIANCE_BOOKING_BOOKING_REQUESTED = "BOOKING_REQUESTED"
COMPLIANCE_BOOKING_PENDING_CLIENT_CONFIRMATION = "PENDING_CLIENT_CONFIRMATION"
COMPLIANCE_BOOKING_CONTRACTOR_NOTIFIED = "CONTRACTOR_NOTIFIED"
COMPLIANCE_BOOKING_AWAITING_CONTRACTOR_RESPONSE = "AWAITING_CONTRACTOR_RESPONSE"
COMPLIANCE_BOOKING_SCHEDULED = "BOOKING_SCHEDULED"
COMPLIANCE_BOOKING_IN_PROGRESS = "BOOKING_IN_PROGRESS"
COMPLIANCE_BOOKING_OPERATIONALLY_COMPLETE = "OPERATIONAL_COMPLETE"

COMPLIANCE_PROOF_NOT_SUBMITTED = "NOT_SUBMITTED"
COMPLIANCE_PROOF_SUBMITTED = "SUBMITTED"
COMPLIANCE_PROOF_VERIFIED = "VERIFIED"

# Authoritative post-execution operational stage (orthogonal to persisted status)
OPERATIONAL_STATUS_WORK_COMPLETED_PENDING_REVIEW = "WORK_COMPLETED_PENDING_REVIEW"

# Completion review lifecycle (landlord/admin human authority)
COMPLETION_REVIEW_PENDING = "PENDING"
COMPLETION_REVIEW_ACCEPTED = "ACCEPTED"
COMPLETION_REVIEW_CLARIFICATION_REQUESTED = "CLARIFICATION_REQUESTED"
COMPLETION_REVIEW_REJECTED = "REJECTED"

ALLOWED_COMPLETION_REVIEW_STATUSES = frozenset(
    {
        COMPLETION_REVIEW_PENDING,
        COMPLETION_REVIEW_ACCEPTED,
        COMPLETION_REVIEW_CLARIFICATION_REQUESTED,
        COMPLETION_REVIEW_REJECTED,
    }
)

COMPLETION_REVIEW_STATUS_LABELS = {
    COMPLETION_REVIEW_PENDING: "Awaiting review",
    COMPLETION_REVIEW_ACCEPTED: "Completion accepted",
    COMPLETION_REVIEW_CLARIFICATION_REQUESTED: "Clarification requested",
    COMPLETION_REVIEW_REJECTED: "Completion rejected",
}
