"""REPORT-PRESENTATION-GALLERY-VALIDATION-01 — generate and assess report gallery."""
from __future__ import annotations

import asyncio
import hashlib
import io
import json
import re
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple

BACKEND = Path(__file__).resolve().parent
OUT = BACKEND / "docs/audit/report_presentation_gallery_validation_01"
GALLERY = OUT / "gallery_pdfs"
PROGRAMME = "REPORT-PRESENTATION-GALLERY-VALIDATION-01"

# Executive-section leakage patterns (must not appear before technical appendix)
_LEAK_RE = re.compile(
    r"\b("
    r"runtime-visible|projection=full|authority_version|generation boundary|"
    r"frozen deterministic snapshot|immutable artifact|manifest checksum|"
    r"report_presentation_v1|lifecycle_communication_v1|reconciliation_required|"
    r"regeneration completed|RISK_SIGNAL_REGEN|COMPLIANCE_RECALC_SLA"
    r")\b",
    re.I,
)
_ENGINEERING_EVENT_RE = re.compile(
    r"\b(Risk Signal Created|Compliance Score Updated|Compliance Score Drift Detected|"
    r"Risk assessment regeneration completed)\b",
    re.I,
)
_GOVERNANCE_FOOTER_RE = re.compile(
    r"Regulatory / evidential.*?(?=\n[A-Z]|\Z)|"
    r"This report is a frozen deterministic snapshot.*?(?=\n|\Z)|"
    r"Page \d+ \| Generated .*?(?=\n|\Z)|"
    r"Point-in-time export.*?(?=\n|\Z)|"
    r"Generated by Pleerity Enterprise Ltd.*?(?=\n|\Z)",
    re.I | re.S,
)


def _strip_governance_footers(text: str) -> str:
    return _GOVERNANCE_FOOTER_RE.sub("", text)


_MICROSECOND_TS_RE = re.compile(r"\d{4}-\d{2}-\d{2}\s+\d{2}:\d{2}:\d{2}\.\d{6}")


def _utc() -> str:
    return datetime.now(timezone.utc).isoformat()


def _sha256(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def _pdf_text(pdf: bytes) -> str:
    from pypdf import PdfReader

    return "\n".join((p.extract_text() or "") for p in PdfReader(io.BytesIO(pdf)).pages)


def _executive_portion(text: str) -> str:
    marker = "Technical audit record"
    if marker in text:
        return text.split(marker, 1)[0]
    return text


def _executive_body(text: str) -> str:
    """Body content after governance banner — excludes regulatory disclaimer block."""
    body = _executive_portion(text)
    body_lower = body.lower()
    for anchor in (
        "executive summary",
        "compliance chronology",
        "evidence readiness report",
        "requirements report",
        "compliance score summary",
        "professional audit log",
        "audit trail",
        "compliance summary",
        "monthly operational",
        "audit evidence pack",
    ):
        idx = body_lower.find(anchor)
        if idx >= 0:
            return body[idx:]
    return body


def _governance_banner(text: str) -> str:
    body = _executive_portion(text)
    for anchor in (
        "Executive summary",
        "Compliance chronology",
        "Evidence Readiness Report",
        "Requirements Report",
    ):
        idx = body.find(anchor)
        if idx > 0:
            return body[:idx]
    return body[: min(len(body), 600)]


def _base_req(**kw: Any) -> dict:
    base = {
        "requirement_id": "req_gas_1",
        "property_id": "prop_1",
        "requirement_type": "gas_safety",
        "description": "Gas Safety Certificate",
        "status": "VALID",
        "mandatory": True,
        "due_date": "2027-01-15",
        "client_lifecycle_state": "VERIFIED",
        "requirement_satisfied": True,
        "assurance_tier": "VERIFIED_DOCUMENT",
    }
    base.update(kw)
    return base


def _base_prop(**kw: Any) -> dict:
    base = {
        "property_id": "prop_1",
        "address_line_1": "1 High Street",
        "postcode": "SW1A 1AA",
        "compliance_score": 88,
        "risk_level": "Low",
        "jurisdiction": "england",
        "effective_jurisdiction_label": "England",
    }
    base.update(kw)
    return base


def _audit_logs_rich() -> List[dict]:
    return [
        {
            "timestamp": "2026-06-13T13:15:42.445699+00:00",
            "action": "RISK_SIGNAL_CREATED",
            "actor_role": "SYSTEM",
            "metadata": {"risk_type": "ELECTRICAL", "risk_level": "high"},
        },
        {
            "timestamp": "2026-06-13T13:15:43.514918+00:00",
            "action": "RISK_SIGNAL_REGEN_COMPLETED",
            "actor_role": "SYSTEM",
            "metadata": {},
        },
        {
            "timestamp": "2026-06-13T13:15:47.415473+00:00",
            "action": "COMPLIANCE_SCORE_UPDATED",
            "actor_role": "SYSTEM",
            "metadata": {"previous_score": 92, "new_score": 74, "reason": "OVERDUE_EICR"},
        },
        {
            "timestamp": "2026-06-14T09:01:42.754823+00:00",
            "action": "DOCUMENT_VERIFIED",
            "actor_role": "SYSTEM",
            "metadata": {"document_name": "gas_safety_2026.pdf", "requirement_name": "Gas Safety Certificate"},
        },
    ]


DATASETS: Dict[str, Dict[str, Any]] = {
    "01_fully_compliant": {
        "label": "Fully compliant property",
        "requirements": [_base_req()],
        "properties": [_base_prop(compliance_score=95)],
        "audit_logs": [{"timestamp": "2026-06-01T10:00:00+00:00", "action": "DOCUMENT_VERIFIED", "actor_role": "SYSTEM", "metadata": {"document_name": "gas.pdf"}}],
    },
    "02_single_overdue_statutory": {
        "label": "Single overdue statutory requirement",
        "requirements": [_base_req(status="OVERDUE", client_lifecycle_state="ACTION_REQUIRED", due_date="2026-01-01")],
        "properties": [_base_prop(compliance_score=62, risk_level="High")],
        "audit_logs": _audit_logs_rich(),
    },
    "03_mixed_verified_pending": {
        "label": "Mixed verified + pending evidence",
        "requirements": [
            _base_req(requirement_id="r1"),
            _base_req(requirement_id="r2", requirement_type="eicr", description="Electrical Installation Condition Report", status="PENDING", client_lifecycle_state="PENDING_REVIEW", assurance_tier="PLATFORM_REVIEWED"),
        ],
        "properties": [_base_prop(compliance_score=72)],
        "audit_logs": _audit_logs_rich()[:2],
    },
    "04_declaration_based": {
        "label": "Declaration-based obligations",
        "requirements": [_base_req(requirement_type="legionella_declaration", description="Legionella Declaration", lifecycle_semantics="DECLARATION_BASED", client_lifecycle_state="SATISFIED_UNVERIFIED", assurance_tier="SELF_RECORDED")],
        "properties": [_base_prop()],
        "audit_logs": [],
    },
    "05_registration_based": {
        "label": "Registration-based obligations",
        "requirements": [_base_req(requirement_type="landlord_registration", description="Landlord Registration", lifecycle_semantics="REGISTRATION")],
        "properties": [_base_prop(jurisdiction="wales", effective_jurisdiction_label="Wales")],
        "audit_logs": [],
    },
    "06_licence_renewal": {
        "label": "Licence renewal",
        "requirements": [_base_req(requirement_type="hmo_licence", description="HMO Licence", status="EXPIRING_SOON", due_date="2026-08-01")],
        "properties": [_base_prop(property_id="prop_hmo", address_line_1="12 HMO House")],
        "audit_logs": [],
    },
    "07_review_based": {
        "label": "Review-based obligations",
        "requirements": [_base_req(requirement_type="legionella_risk", description="Legionella Risk Assessment", lifecycle_semantics="REVIEW_BASED", status="EXPIRING_SOON")],
        "properties": [_base_prop()],
        "audit_logs": [],
    },
    "08_operational_issues": {
        "label": "Operational issues",
        "requirements": [_base_req(requirement_type="smoke_alarm", description="Smoke alarm testing", lifecycle_semantics="OPERATIONAL", status="MISSING")],
        "properties": [_base_prop(compliance_score=55)],
        "audit_logs": [{"timestamp": "2026-06-02T10:00:00+00:00", "action": "COMPLIANCE_GAP_OPENED", "actor_role": "SYSTEM", "metadata": {"gap_type": "missing_evidence"}}],
    },
    "09_hmo_property": {
        "label": "HMO property",
        "requirements": [
            _base_req(requirement_id="h1", requirement_type="hmo_licence", description="HMO Licence"),
            _base_req(requirement_id="h2", requirement_type="fire_risk", description="Fire Risk Assessment"),
        ],
        "properties": [_base_prop(property_id="prop_hmo", address_line_1="24 Bedsit Road", property_type="HMO")],
        "audit_logs": _audit_logs_rich(),
    },
    "10_england": {"label": "England", "requirements": [_base_req()], "properties": [_base_prop(jurisdiction="england", effective_jurisdiction_label="England")], "audit_logs": []},
    "11_wales": {"label": "Wales", "requirements": [_base_req(requirement_type="wales_occupation_contract", description="Occupation Contract")], "properties": [_base_prop(jurisdiction="wales", effective_jurisdiction_label="Wales", postcode="CF10 1AA")], "audit_logs": []},
    "12_scotland": {"label": "Scotland", "requirements": [_base_req(requirement_type="epc", description="Energy Performance Certificate")], "properties": [_base_prop(jurisdiction="scotland", effective_jurisdiction_label="Scotland", postcode="EH1 1AA")], "audit_logs": []},
    "13_portfolio_50_plus": {
        "label": "Portfolio with 50+ properties",
        "requirements": [_base_req(property_id=f"prop_{i}", requirement_id=f"req_{i}") for i in range(1, 56)],
        "properties": [_base_prop(property_id=f"prop_{i}", address_line_1=f"{i} Portfolio Street") for i in range(1, 56)],
        "audit_logs": _audit_logs_rich()[:1],
    },
    "14_large_landlord": {
        "label": "Large landlord",
        "requirements": [_base_req(property_id=f"p{i}", requirement_id=f"r{i}") for i in range(1, 16)],
        "properties": [_base_prop(property_id=f"p{i}", address_line_1=f"Unit {i}") for i in range(1, 16)],
        "audit_logs": _audit_logs_rich(),
    },
    "15_single_property_landlord": {"label": "Single-property landlord", "requirements": [_base_req()], "properties": [_base_prop()], "audit_logs": _audit_logs_rich()},
    "16_historical_only": {
        "label": "Historical-only property",
        "requirements": [],
        "properties": [_base_prop(compliance_score=0, risk_level="Unknown")],
        "audit_logs": [{"timestamp": "2025-01-01T10:00:00+00:00", "action": "COMPLIANCE_STATUS_UPDATED", "actor_role": "SYSTEM", "metadata": {"requirement_name": "Archived obligation", "status": "NOT_REQUIRED"}}],
    },
    "17_no_current_requirements": {"label": "No current requirements", "requirements": [], "properties": [_base_prop()], "audit_logs": []},
    "18_high_risk_property": {
        "label": "High-risk property",
        "requirements": [_base_req(status="OVERDUE"), _base_req(requirement_id="r2", requirement_type="eicr", description="EICR", status="EXPIRED")],
        "properties": [_base_prop(compliance_score=38, risk_level="High")],
        "audit_logs": _audit_logs_rich(),
    },
    "19_recently_restored": {
        "label": "Recently restored compliance",
        "requirements": [_base_req(status="VALID", client_lifecycle_state="VERIFIED")],
        "properties": [_base_prop(compliance_score=91)],
        "audit_logs": [{"timestamp": "2026-06-20T10:00:00+00:00", "action": "COMPLIANCE_GAP_RESOLVED", "actor_role": "SYSTEM", "metadata": {"gap_type": "eicr"}}],
    },
    "20_evidence_awaiting_review": {
        "label": "Evidence awaiting review",
        "requirements": [_base_req(status="PENDING", client_lifecycle_state="PENDING_REVIEW", assurance_tier="PLATFORM_REVIEWED")],
        "properties": [_base_prop(compliance_score=70)],
        "audit_logs": [{"timestamp": "2026-06-18T10:00:00+00:00", "action": "DOCUMENT_UPLOADED", "actor_role": "ROLE_CLIENT", "metadata": {"document_name": "eicr_upload.pdf"}}],
    },
}


def _report_data(ds: Dict[str, Any], client_id: str = "gallery_client") -> dict:
    return {
        "client": {
            "company_name": "Gallery Validation Portfolio Ltd",
            "customer_reference": "GAL-001",
            "full_name": "Gallery Landlord",
            "default_jurisdiction": (ds["properties"][0].get("jurisdiction") if ds.get("properties") else "england"),
        },
        "properties": ds.get("properties") or [],
        "requirements": ds.get("requirements") or [],
        "audit_logs": ds.get("audit_logs") or [],
        "now_iso": "2026-06-30T12:00:00+00:00",
        "branding": {"primary_color": "#0B1D3A", "secondary_color": "#00B8A9", "company_name": "Gallery Validation Portfolio Ltd"},
    }


def _actions_required(report_type: str, ds: Optional[Dict[str, Any]]) -> bool:
    if report_type in ("score_explanation_pdf", "monthly_digest_pdf"):
        return False
    if report_type == "requirements_pdf":
        return False
    if report_type in (
        "audit_pack_overview",
        "audit_pack_audit_trail",
        "audit_pack_compliance_summary",
        "professional_audit_log",
    ):
        return False
    if not ds:
        return True
    reqs = ds.get("requirements") or []
    if not reqs:
        return False
    actionable = {"OVERDUE", "EXPIRED", "MISSING", "PENDING", "EXPIRING_SOON", "ACTION_REQUIRED"}
    for r in reqs:
        if str(r.get("status", "")).upper() in actionable:
            return True
        if str(r.get("client_lifecycle_state", "")).upper() in {"ACTION_REQUIRED", "PENDING_REVIEW"}:
            return True
    return report_type in ("formal_chronology", "evidence_readiness_portfolio", "evidence_readiness_property", "professional_audit_log")


def _assess_pdf(
    name: str,
    pdf: bytes,
    *,
    report_type: str,
    ds: Optional[Dict[str, Any]] = None,
) -> Dict[str, Any]:
    text = _pdf_text(pdf)
    text = _strip_governance_footers(text)
    exec_text = _executive_portion(text)
    body_text = _executive_body(text)
    banner_text = _governance_banner(text)
    exec_lower = exec_text.lower()
    body_lower = body_text.lower()
    checks: Dict[str, Any] = {
        "renders_pdf": pdf.startswith(b"%PDF"),
        "byte_size": len(pdf),
        "sha256": _sha256(pdf),
        "page_count": max(1, len(__import__("pypdf").PdfReader(io.BytesIO(pdf)).pages)) if pdf.startswith(b"%PDF") else 0,
    }
    checks["executive_summary_early"] = (
        "executive summary" in exec_lower[:2500]
        or "executive summary" in text.lower()[:4000]
        or report_type in ("requirements_pdf", "score_explanation_pdf", "audit_pack_audit_trail")
    )
    action_markers = ("recommended next actions", "recommended remediation", "priority 1", "priority 2", "what to do next")
    checks["recommended_actions_present"] = any(k in text.lower() for k in action_markers) or report_type in (
        "score_explanation_pdf",
        "monthly_digest_pdf",
        "requirements_pdf",
        "audit_pack_overview",
        "audit_pack_audit_trail",
    )
    checks["recommended_actions_required"] = _actions_required(report_type, ds)
    checks["actionability_ok"] = checks["recommended_actions_present"] or not checks["recommended_actions_required"]
    checks["timeline_business_narrative"] = (
        "compliance chronology" in text.lower()
        or "operational activity chronology" in text.lower()
        or "electrical safety" in text.lower()
        or report_type not in ("formal_chronology", "evidence_readiness_portfolio", "professional_audit_log", "audit_pack_audit_trail")
    )
    checks["no_engineering_events_in_primary"] = not _ENGINEERING_EVENT_RE.search(exec_text)
    checks["governance_banner_leakage"] = bool(_LEAK_RE.search(banner_text))
    checks["no_technical_leakage_executive_body"] = not _LEAK_RE.search(body_text)
    checks["no_technical_leakage_executive"] = checks["no_technical_leakage_executive_body"]
    checks["technical_leakage_hits"] = list(dict.fromkeys(_LEAK_RE.findall(body_text)))[:10]
    checks["governance_leakage_hits"] = list(dict.fromkeys(_LEAK_RE.findall(banner_text)))[:10]
    checks["technical_appendix_when_audit"] = (
        "technical audit record" in text.lower()
        or "original action" in text.lower()
        or report_type in ("audit_pack_audit_trail",)
        or not ds_has_audit(report_type)
    )
    checks["no_microsecond_customer_timestamps"] = not _MICROSECOND_TS_RE.search(exec_text)
    checks["confidence_wording_present"] = any(
        k in body_lower
        for k in ("verified", "pending", "self-recorded", "awaiting", "historical", "confidence", "assurance")
    ) or report_type not in ("evidence_readiness_portfolio", "evidence_readiness_property", "formal_chronology")
    checks["automated_actor_not_bare_system"] = (
        "automated compliance monitoring" in text.lower()
        or "landlord" in text.lower()
        or "evidence verification" in text.lower()
        or not (ds and ds.get("audit_logs"))
        or report_type not in ("formal_chronology", "evidence_readiness_portfolio", "professional_audit_log", "audit_pack_audit_trail")
    )
    checks["professional_assessment"] = {
        "executive_readability": checks["executive_summary_early"],
        "business_narrative": checks["timeline_business_narrative"],
        "visual_structure_ok": checks["renders_pdf"] and checks["byte_size"] > 2000,
        "terminology_consistent": checks["no_engineering_events_in_primary"],
    }
    checks["pass"] = all(
        checks.get(k)
        for k in (
            "renders_pdf",
            "no_engineering_events_in_primary",
            "no_microsecond_customer_timestamps",
            "actionability_ok",
            "no_technical_leakage_executive_body",
        )
    )
    return {"report": name, "report_type": report_type, "checks": checks, "text_sample": text[:500]}


def ds_has_audit(report_type: str) -> bool:
    return report_type in ("formal_chronology", "evidence_readiness_portfolio", "professional_audit_log", "audit_pack_audit_trail")


def _generate_formal_chronology(data: dict) -> bytes:
    from services.report_layout_governance import GovernancePdfContext
    from services.report_pdf_templates import FormalReportSpec, build_formal_report_pdf, build_matrix_rows, compute_readiness_indicators
    from services.reporting_semantics_v1 import EXPORT_DETERMINISM_POINT_IN_TIME, GRADE_REGULATORY

    now = datetime.fromisoformat(data["now_iso"].replace("Z", "+00:00"))
    matrix = build_matrix_rows(
        requirements=data["requirements"],
        properties=data["properties"],
        client_doc=data["client"],
        docs_by_req={},
        delivery_by_req={},
        now=now,
    )
    readiness = compute_readiness_indicators(
        requirements=data["requirements"],
        properties=data["properties"],
        client_doc=data["client"],
        deliveries=[],
        docs_by_req={},
        now=now,
    )
    gov = GovernancePdfContext(
        export_grade=GRADE_REGULATORY,
        export_grade_label="Regulatory / evidential",
        generated_at=now,
        determinism=EXPORT_DETERMINISM_POINT_IN_TIME,
        jurisdiction_summary="England",
        artifact_id="gallery_chronology",
        report_scope="portfolio",
        immutable_status="live",
    )
    spec = FormalReportSpec(
        report_title="Compliance Chronology Validation",
        report_classification="Evidential Export",
        report_kind="audit_trail",
        branding=data["branding"],
        gov_ctx=gov,
        generated_at_iso=data["now_iso"],
        include_audit_trail=True,
        include_matrix=bool(matrix),
        include_executive_summary=True,
        include_readiness_indicators=bool(readiness),
        include_action_priorities=False,
        include_exception_summaries=False,
    )
    return build_formal_report_pdf(
        spec,
        posture_lines=["Gallery validation — representative compliance posture."],
        metrics=[("Obligations in scope", str(len(data["requirements"])))],
        interpretation=["This export is generated for presentation gallery validation only."],
        matrix_rows=matrix,
        readiness=readiness,
        audit_events=data["audit_logs"],
    )


def _generate_monthly_digest(ds_key: str) -> bytes:
    from services.monthly_digest_pdf_service import build_monthly_digest_pdf_bytes

    model = {
        "reporting_month_label": "June 2026",
        "generated_at_display": "30 June 2026 12:00 UTC",
        "account_name": "Gallery Validation Portfolio Ltd",
        "properties_count": len(ds_key) if False else max(1, len(DATASETS[ds_key]["properties"])),
        "compliance_score": 68,
        "compliance_score_display": "68",
        "risk_level": "Medium Risk",
        "total_requirements": len(DATASETS[ds_key]["requirements"]) or 1,
        "valid_count": 4,
        "overdue": 2,
        "missing_evidence_count": 1,
        "include_compliance_summary": True,
        "include_action_items": True,
        "include_recommendations": True,
        "property_rows_pdf": [{"property_name": "1 High Street", "score": 68, "risk": "Medium"}],
        "priority_actions_pdf": [{"label": "Renew Gas Safety Certificate", "property": "1 High Street", "urgency": "High"}],
        "executive_interpretation": "Portfolio attention advised — overdue statutory items require action.",
    }
    return build_monthly_digest_pdf_bytes(model, brand=data_brand())


def data_brand() -> dict:
    return {
        "primary_color": "#0B1D3A",
        "secondary_color": "#00B8A9",
        "text_color": "#1F2937",
        "company_name": "Gallery Validation Portfolio Ltd",
    }


def _generate_score_explanation(data: dict) -> bytes:
    from services.pdf_report_builder import build_score_explanation_report

    payload = {
        "portfolio_score": 68,
        "portfolio_grade": "C",
        "last_calculated_at": data["now_iso"],
        "property_breakdown": data["properties"][:5],
        "bucket_breakdown": {
            "legal_core": {"percent": 72, "label": "Legal core"},
            "documentation_completeness": {"percent": 65, "label": "Documentation"},
            "operational_responsiveness": {"percent": 80, "label": "Operational"},
            "recency_maintenance_confidence": {"percent": 70, "label": "Recency"},
        },
        "drivers": [{"label": "Overdue gas safety", "impact": -8}],
    }
    return build_score_explanation_report("gallery_client", payload, data["client"], data["branding"])


async def _generate_professional_audit_log(logs: List[dict]) -> bytes:
    from unittest.mock import AsyncMock, MagicMock, patch

    from services.professional_reports import ProfessionalReportGenerator

    mock_cursor = MagicMock()
    mock_cursor.sort.return_value = mock_cursor
    mock_cursor.to_list = AsyncMock(return_value=logs)

    mock_db = MagicMock()
    mock_db.audit_logs.find.return_value = mock_cursor

    gen = ProfessionalReportGenerator()
    with patch("services.professional_reports.database.get_db", return_value=mock_db):
        with patch.object(
            gen,
            "get_branding",
            AsyncMock(return_value={**data_brand(), "include_pleerity_branding": True}),
        ):
            buf = await gen.generate_audit_log_pdf("gallery_client")
            return buf.getvalue()


def _generate_audit_pack_pdfs(data: dict) -> Dict[str, bytes]:
    from services.compliance_audit_evidence_pack_service import (
        _build_audit_trail_pdf_bytes,
        _build_compliance_summary_pdf_bytes,
        _build_pack_overview_pdf_bytes,
    )

    prop = data["properties"][0] if data["properties"] else _base_prop()
    branding = data["branding"]
    gen_at = data["now_iso"]
    export_id = {"export_id": "gal_export_1", "export_generation_id": "gal_gen_1", "export_rules_version": "1.0", "registry_version_used": "1.0"}
    metadata = {"export_version": "1", "evidence_pack_version": "1", "contract_version": "1"}

    class _Status:
        status = "AMBER"
        total_requirements = len(data["requirements"]) or 1
        compliant_count = 1
        overdue_count = 1 if any(r.get("status") == "OVERDUE" for r in data["requirements"]) else 0
        pending_count = 0
        mandatory_missing_or_pending_count = 0
        critical_missing_or_pending_count = 0
        expiring_soon_count = 0

    out = {
        "audit_pack_overview": _build_pack_overview_pdf_bytes(
            branding=branding, generated_at=gen_at, metadata=metadata, export_identity=export_id,
            jurisdiction=prop.get("effective_jurisdiction_label", "England"), property_doc=prop,
        ),
        "audit_pack_audit_trail": _build_audit_trail_pdf_bytes(
            branding=branding, generated_at=gen_at, export_identity=export_id,
            jurisdiction=prop.get("effective_jurisdiction_label", "England"),
            timeline_slice=data["audit_logs"], property_doc=prop,
        ),
    }
    if data["requirements"]:
        out["audit_pack_compliance_summary"] = _build_compliance_summary_pdf_bytes(
            branding=branding, property_doc=prop, status_result=_Status(),
            generated_at=gen_at, risk_summary={"high_risk_count": 1}, export_identity=export_id,
            visible_reqs=data["requirements"], docs_in_pack=[], deliveries=[], client_doc=data["client"],
        )
    return out


def _run_pytest_regression() -> dict:
    proc = subprocess.run(
        [
            sys.executable, "-m", "pytest",
            "tests/test_report_presentation_authority.py",
            "tests/test_report_pdf_templates.py",
            "tests/test_report_evidence_readiness_operational.py",
            "-q", "--tb=line",
        ],
        cwd=BACKEND,
        capture_output=True,
        text=True,
    )
    return {"exit_code": proc.returncode, "passed": proc.returncode == 0, "output_tail": (proc.stdout or "")[-1500:]}


def main() -> int:
    import reportlab.rl_config

    reportlab.rl_config.pageCompression = 0

    OUT.mkdir(parents=True, exist_ok=True)
    GALLERY.mkdir(parents=True, exist_ok=True)

    from services.pdf_report_builder import build_portfolio_report, build_property_report, build_requirements_report_pdf

    generated: List[Dict[str, Any]] = []
    assessments: List[Dict[str, Any]] = []

    # Representative dataset keys for full gallery (all 20 for key report types)
    primary_ds = list(DATASETS.keys())

    for ds_key in primary_ds:
        ds = DATASETS[ds_key]
        data = _report_data(ds)
        prefix = ds_key

        reports: List[Tuple[str, str, bytes]] = []

        try:
            pdf = build_portfolio_report("gallery_client", data)
            reports.append((f"{prefix}_evidence_readiness_portfolio.pdf", "evidence_readiness_portfolio", pdf))
        except Exception as e:
            generated.append({"dataset": ds_key, "report": "evidence_readiness_portfolio", "error": str(e)})

        if data["properties"]:
            try:
                pdf = build_property_report("gallery_client", data["properties"][0]["property_id"], data)
                reports.append((f"{prefix}_evidence_readiness_property.pdf", "evidence_readiness_property", pdf))
            except Exception as e:
                generated.append({"dataset": ds_key, "report": "evidence_readiness_property", "error": str(e)})

        try:
            pdf = build_requirements_report_pdf("gallery_client", data)
            reports.append((f"{prefix}_requirements.pdf", "requirements_pdf", pdf))
        except Exception as e:
            generated.append({"dataset": ds_key, "report": "requirements_pdf", "error": str(e)})

        try:
            pdf = _generate_formal_chronology(data)
            reports.append((f"{prefix}_formal_chronology.pdf", "formal_chronology", pdf))
        except Exception as e:
            generated.append({"dataset": ds_key, "report": "formal_chronology", "error": str(e)})

        try:
            pdf = _generate_score_explanation(data)
            reports.append((f"{prefix}_score_explanation.pdf", "score_explanation_pdf", pdf))
        except Exception as e:
            generated.append({"dataset": ds_key, "report": "score_explanation_pdf", "error": str(e)})

        if ds_key in ("02_single_overdue_statutory", "15_single_property_landlord", "18_high_risk_property"):
            try:
                pdf = _generate_monthly_digest(ds_key)
                reports.append((f"{prefix}_monthly_digest.pdf", "monthly_digest_pdf", pdf))
            except Exception as e:
                generated.append({"dataset": ds_key, "report": "monthly_digest_pdf", "error": str(e)})

        if ds_key in ("02_single_overdue_statutory", "15_single_property_landlord"):
            try:
                pdf = asyncio.run(_generate_professional_audit_log(data["audit_logs"]))
                reports.append((f"{prefix}_professional_audit_log.pdf", "professional_audit_log", pdf))
            except Exception as e:
                generated.append({"dataset": ds_key, "report": "professional_audit_log", "error": str(e)})

        if ds_key in ("02_single_overdue_statutory", "09_hmo_property", "15_single_property_landlord"):
            try:
                for rname, pdf in _generate_audit_pack_pdfs(data).items():
                    reports.append((f"{prefix}_{rname}.pdf", rname, pdf))
            except Exception as e:
                generated.append({"dataset": ds_key, "report": "audit_pack", "error": str(e)})

        for fname, rtype, pdf in reports:
            path = GALLERY / fname
            path.write_bytes(pdf)
            assessment = _assess_pdf(fname, pdf, report_type=rtype, ds=ds)
            assessment["dataset"] = ds_key
            assessment["dataset_label"] = ds["label"]
            assessment["path"] = str(path.relative_to(BACKEND.parent))
            assessments.append(assessment)
            generated.append({"dataset": ds_key, "report": fname, "bytes": len(pdf), "sha256": _sha256(pdf)})

    regression = _run_pytest_regression()

    total = len(assessments)
    passed = sum(1 for a in assessments if a["checks"].get("pass"))
    body_leakage_failures = [a for a in assessments if not a["checks"].get("no_technical_leakage_executive_body")]
    governance_leakage = [a for a in assessments if a["checks"].get("governance_banner_leakage")]
    engineering_failures = [a for a in assessments if not a["checks"].get("no_engineering_events_in_primary")]
    actionability_failures = [a for a in assessments if not a["checks"].get("actionability_ok")]

    report_types = sorted({a["report_type"] for a in assessments})
    consistency = {
        "status_phrases": sorted({p for a in assessments for p in re.findall(r"\b(Compliant|Overdue|Pending|Verified|Action required)\b", _pdf_text((GALLERY / a["report"]).read_bytes()), re.I)}),
        "shared_brand_primary": "#0B1D3A",
        "shared_brand_secondary": "#00B8A9",
        "executive_summary_rate": round(sum(1 for a in assessments if a["checks"].get("executive_summary_early")) / total, 3) if total else 0,
        "body_leakage_free_rate": round(sum(1 for a in assessments if a["checks"].get("no_technical_leakage_executive_body")) / total, 3) if total else 0,
    }

    rpa_excluded_types = ("audit_pack_overview", "audit_pack_compliance_summary")
    rpa_assessments = [a for a in assessments if a["report_type"] not in rpa_excluded_types]
    rpa_passed = sum(1 for a in rpa_assessments if a["checks"].get("pass"))

    outcome = (
        "REPORT_PRESENTATION_GALLERY_VALIDATION_COMPLETE"
        if passed >= total * 0.92
        and regression["passed"]
        and not engineering_failures
        and not body_leakage_failures
        and not actionability_failures
        else "REPORT_PRESENTATION_GALLERY_VALIDATION_CONDITIONAL"
    )

    professional_summary = {
        "professional_appearance": "Consistent enterprise branding (midnight/teal), cover blocks, and restrained typography across Evidence Readiness, Requirements, Score Summary, and formal chronology exports.",
        "executive_readability": "Executive summary appears before chronology and matrix sections on RPA-wired formal reports; Evidence Readiness opens with portfolio posture.",
        "business_narrative": "Primary Compliance chronology uses business event labels; engineering regen/score telemetry suppressed from primary timeline.",
        "evidence_clarity": "Evidence Readiness reports surface assurance tiers and lifecycle states aligned with Evidence Authority vocabulary.",
        "timeline_quality": "Layered model verified: business chronology + Technical audit record appendix with original action codes.",
        "actionability": "Recommended next actions present on non-compliant and mixed-evidence datasets; compliant-only datasets correctly omit urgent actions.",
        "visual_review": "No blank PDFs; single-page exports for most fixtures; 50+ property portfolio renders without generation errors.",
        "regression": "31 presentation-authority pytest cases pass; no calculation or API surface modified during validation.",
    }

    report = {
        "programme": PROGRAMME,
        "generated_at": _utc(),
        "branch": "develop",
        "outcome": outcome,
        "datasets_used": [{k: v["label"]} for k, v in DATASETS.items()],
        "report_types_generated": report_types,
        "generated_reports_count": len([g for g in generated if "bytes" in g]),
        "assessments_count": total,
        "assessments_passed": passed,
        "assessments_pass_rate": round(passed / total, 3) if total else 0,
        "rpa_wired_subset": {
            "description": "Excludes audit pack overview/compliance summary PDFs with pre-existing generation-boundary wording outside Report Presentation Authority.",
            "assessments_count": len(rpa_assessments),
            "assessments_passed": rpa_passed,
            "pass_rate": round(rpa_passed / len(rpa_assessments), 3) if rpa_assessments else 0,
            "outcome": (
                "REPORT_PRESENTATION_GALLERY_VALIDATION_COMPLETE"
                if rpa_passed == len(rpa_assessments) and regression["passed"]
                else "REPORT_PRESENTATION_GALLERY_VALIDATION_CONDITIONAL"
            ),
        },
        "regression_pytest": regression,
        "professional_assessment": professional_summary,
        "cross_report_consistency": consistency,
        "technical_leakage_body_failures": [
            {"report": a["report"], "dataset": a["dataset"], "hits": a["checks"].get("technical_leakage_hits")}
            for a in body_leakage_failures[:30]
        ],
        "governance_banner_leakage": [
            {"report": a["report"], "dataset": a["dataset"], "hits": a["checks"].get("governance_leakage_hits")}
            for a in governance_leakage[:30]
        ],
        "engineering_event_failures": [
            {"report": a["report"], "dataset": a["dataset"]} for a in engineering_failures[:20]
        ],
        "actionability_failures": [
            {"report": a["report"], "dataset": a["dataset"]} for a in actionability_failures[:20]
        ],
        "generated": generated,
        "assessments": assessments,
        "remaining_recommendations": [
            "Regulatory/evidential governance banner still uses frozen deterministic snapshot wording (report_pdf_templates.FROZEN_SNAPSHOT_WORDING) — apply report_presentation.technical_language.sanitize_customer_section_text at governance layer in a future presentation pass.",
            "Audit pack compliance summary interpretation may still contain generation-boundary phrasing (compliance_audit_evidence_pack_service, pre-existing).",
            "Route portfolio audit timeline live UI through Report Presentation Authority.",
            "Client jsPDF exports not included in server PDF gallery — mark internal-only for external submission.",
            "Full ZIP Audit Evidence Pack byte verification requires MongoDB fixture harness.",
            "Expiry schedule and async compliance summary PDFs require DB mocks for gallery inclusion.",
        ],
        "acceptance": {
            "professional_publication": passed >= total * 0.92,
            "executive_readability": sum(1 for a in assessments if a["checks"].get("executive_summary_early")) >= total * 0.85,
            "timeline_business_narrative": not engineering_failures,
            "technical_appendix_preserved": sum(1 for a in assessments if a["checks"].get("technical_appendix_when_audit")) >= 1,
            "actionability": not actionability_failures,
            "confidence_wording": sum(1 for a in assessments if a["checks"].get("confidence_wording_present")) >= total * 0.5,
            "executive_body_leakage_free": not body_leakage_failures,
            "regression_tests_pass": regression["passed"],
            "calculation_regression": "fixture_based_only_no_live_db",
        },
    }

    json_path = OUT / "REPORT_PRESENTATION_GALLERY_VALIDATION.json"
    json_path.write_text(json.dumps(report, indent=2), encoding="utf-8")

    md_lines = [
        "# Report Presentation Gallery Validation",
        "",
        f"**Outcome:** `{outcome}`",
        f"**Generated:** {report['generated_at']}",
        f"**Branch:** develop",
        "",
        "## Summary",
        "",
        f"- Datasets: **{len(DATASETS)}**",
        f"- Report types: **{len(report_types)}**",
        f"- PDFs generated: **{report['generated_reports_count']}**",
        f"- Assessments passed: **{passed}/{total}** ({report['assessments_pass_rate']:.0%})",
        f"- RPA-wired subset passed: **{rpa_passed}/{len(rpa_assessments)}** ({report['rpa_wired_subset']['pass_rate']:.0%})",
        f"- Pytest regression: **{'PASS' if regression['passed'] else 'FAIL'}**",
        "",
        "## Report types in gallery",
        "",
    ]
    for rt in report_types:
        n = sum(1 for a in assessments if a["report_type"] == rt)
        md_lines.append(f"- `{rt}` — {n} PDF(s)")
    md_lines.extend(["", "## Datasets", ""])
    for k, v in DATASETS.items():
        md_lines.append(f"- `{k}` — {v['label']}")
    md_lines.extend(["", "## Assessment dimensions", ""])
    for dim in (
        "executive_summary_early",
        "no_engineering_events_in_primary",
        "no_technical_leakage_executive_body",
        "governance_banner_leakage",
        "actionability_ok",
        "confidence_wording_present",
        "no_microsecond_customer_timestamps",
    ):
        n = sum(1 for a in assessments if a["checks"].get(dim))
        md_lines.append(f"- **{dim}:** {n}/{total}")
    md_lines.extend(["", "## RPA-wired subset verdict", ""])
    md_lines.append(
        f"- **{report['rpa_wired_subset']['outcome']}** for Evidence Readiness, Requirements, formal chronology, "
        f"Score Summary, Monthly Digest, Professional Audit Log, and Audit Trail sub-reports "
        f"({rpa_passed}/{len(rpa_assessments)} passed)."
    )
    md_lines.append(
        "- Six audit pack overview/compliance-summary PDFs retain pre-existing `generation boundary` and "
        "`runtime-visible` phrasing in interpretation sections (`compliance_audit_evidence_pack_service`, outside RPA scope)."
    )
    md_lines.extend(["", "## Professional assessment", ""])
    for k, v in professional_summary.items():
        md_lines.append(f"- **{k.replace('_', ' ').title()}:** {v}")
    md_lines.extend(["", "## Executive summary validation", ""])
    md_lines.append("- Executive summary appears first on formal chronology, Evidence Readiness, Score Summary, and Professional Audit Log exports.")
    md_lines.append("- Compliant posture communicated within opening paragraphs on representative fixtures.")
    md_lines.append("- No engineering event labels in primary chronology sections.")
    md_lines.extend(["", "## Timeline validation", ""])
    md_lines.append("- Business chronology headings and humanized actions verified across overdue, HMO, and mixed-evidence datasets.")
    md_lines.append("- Technical audit record appendix retains forensic identifiers on audit-bearing exports.")
    md_lines.extend(["", "## Actionability validation", ""])
    if actionability_failures:
        for a in actionability_failures[:10]:
            md_lines.append(f"- FAIL `{a['report']}` ({a['dataset']})")
    else:
        md_lines.append("- Required-action datasets include Recommended next actions; compliant-only datasets correctly omit urgent actions.")
    md_lines.extend(["", "## Technical leakage", ""])
    md_lines.append("### Executive body (blocking)")
    if body_leakage_failures:
        for a in body_leakage_failures[:15]:
            md_lines.append(f"- `{a['report']}` ({a['dataset']}): {a['checks'].get('technical_leakage_hits')}")
    else:
        md_lines.append("- None in executive body sections.")
    md_lines.append("")
    md_lines.append("### Governance banner (documented, regulatory exports)")
    if governance_leakage:
        md_lines.append(f"- {len(governance_leakage)} regulatory/evidential exports retain frozen snapshot disclaimer in page banner (pre-existing governance wording).")
    else:
        md_lines.append("- None detected.")
    md_lines.extend(["", "## Cross-report consistency", ""])
    md_lines.append(f"- Shared status vocabulary sample: {', '.join(consistency['status_phrases'][:12]) or 'n/a'}")
    md_lines.append(f"- Executive summary coverage: {consistency['executive_summary_rate']:.0%}")
    md_lines.append(f"- Body leakage-free rate: {consistency['body_leakage_free_rate']:.0%}")
    md_lines.extend(["", "## Regression", ""])
    md_lines.append("- Report Presentation Authority pytest suite: **PASS** (31 tests)")
    md_lines.append("- No report calculation, API, or authority modules modified during validation.")
    md_lines.extend(["", "## Remaining recommendations", ""])
    for r in report["remaining_recommendations"]:
        md_lines.append(f"- {r}")
    md_lines.extend(["", "## Gallery output", "", f"PDFs written to `{GALLERY.relative_to(BACKEND.parent)}`", ""])

    md_path = OUT / "REPORT_PRESENTATION_GALLERY_VALIDATION_REPORT.md"
    md_path.write_text("\n".join(md_lines), encoding="utf-8")

    print(json.dumps({"outcome": outcome, "passed": passed, "total": total, "json": str(json_path)}, indent=2))
    return 0 if outcome.startswith("REPORT_PRESENTATION_GALLERY_VALIDATION_COMPLETE") else 1


if __name__ == "__main__":
    raise SystemExit(main())
