import asyncio
import io
import json
import zipfile
from unittest.mock import AsyncMock, MagicMock, patch

from database import database as db_singleton
from services import compliance_audit_evidence_pack_service as svc


def _find_one_side_effect(filter_q, *_args, **_kwargs):
    fq = filter_q or {}
    if fq.get("property_id") == "p1" and fq.get("client_id") == "c1":
        return {
            "property_id": "p1",
            "client_id": "c1",
            "address_line_1": "Laurel Gardens",
            "city": "London",
            "postcode": "E1 1AA",
            "nickname": "Laurel Gardens",
            "effective_jurisdiction_label": "England",
        }
    if fq.get("client_id") == "c1":
        return {"client_id": "c1", "company_name": "Premier Property Management Ltd"}
    if "filename" in fq:
        return None
    return None


def _build_chain(rows):
    c3 = MagicMock()
    c3.to_list = AsyncMock(return_value=rows)
    c2 = MagicMock()
    c2.limit = MagicMock(return_value=c3)
    c1 = MagicMock()
    c1.sort = MagicMock(return_value=c2)
    return c1


def test_enterprise_pack_deterministic_structure_and_governance():
    req_active = {
        "requirement_id": "r1",
        "client_id": "c1",
        "property_id": "p1",
        "requirement_type": "gas_safety",
        "requirement_code": "GAS",
        "status": "OVERDUE",
        "mandatory": True,
        "evidence_authority_synced_at": "2026-01-01T00:00:00+00:00",
        "evidence_authority": {"version": 1, "state": "VERIFIED_CURRENT"},
    }
    req_hidden = {
        "requirement_id": "ghost_hidden_1",
        "client_id": "c1",
        "property_id": "p1",
        "requirement_type": "legacy_type",
        "status": "PENDING",
    }

    mock_db = MagicMock()
    mock_db.properties.find_one = AsyncMock(side_effect=_find_one_side_effect)
    mock_db.clients.find_one = AsyncMock(side_effect=_find_one_side_effect)
    mock_db.requirements.find = MagicMock(return_value=MagicMock(to_list=AsyncMock(return_value=[req_active, req_hidden])))
    mock_db.documents.find = MagicMock(return_value=MagicMock(to_list=AsyncMock(return_value=[])))
    mock_db.audit_logs.find = MagicMock(
        return_value=_build_chain(
            [
                {
                    "action": "REQUIREMENT_STATUS_CHANGED",
                    "timestamp": "2026-01-03T00:00:00+00:00",
                    "metadata": {"property_id": "p1", "requirement_id": "ghost_hidden_1"},
                    "resource_type": "requirement",
                    "resource_id": "ghost_hidden_1",
                }
            ]
        )
    )
    mock_db.tenant_delivery_proofs.find = MagicMock(return_value=_build_chain([]))
    mock_db.compliance_audit_packs.insert_one = AsyncMock()
    mock_db.compliance_audit_packs.find_one = AsyncMock(return_value=None)

    uploaded = {}

    async def fake_upload(filename, data, metadata):
        uploaded["filename"] = filename
        uploaded["zip"] = data
        uploaded["metadata"] = metadata
        return "507f1f77bcf86cd799439011"

    with (
        patch.object(db_singleton, "get_db", return_value=mock_db),
        patch.object(
            svc,
            "filter_requirement_rows_for_client_runtime_surfaces",
            new=AsyncMock(return_value=[req_active]),
        ),
        patch.object(
            svc,
            "resolve_branding",
            new=AsyncMock(
                return_value=MagicMock(
                    source="pleerity",
                    company_name="Pleerity Enterprise Ltd",
                    to_report_dict=lambda: {
                        "brand_company_name": "Pleerity Enterprise Ltd",
                        "company_name": "Pleerity Enterprise Ltd",
                        "primary_color": "#0B1D3A",
                        "pdf_footer_generated_by": "Generated by Pleerity Enterprise Ltd",
                        "pdf_footer_contact_line": "pleerityenterprise.co.uk",
                    },
                )
            ),
        ),
        patch.object(svc, "_upload_zip_gridfs", new=fake_upload),
        patch("services.compliance_audit_evidence_pack_service.create_audit_log", new_callable=AsyncMock),
    ):
        summary = asyncio.run(
            svc.build_compliance_audit_pack(
                client_id="c1",
                property_id="p1",
                initiated_by_user_id="u1",
                initiated_by_role="ROLE_CLIENT_ADMIN",
            )
        )

    assert summary["overall_compliance_status"] in {"ACTION REQUIRED", "HIGH RISK"}
    assert uploaded["filename"].startswith("CVP_Audit_Evidence_Pack_")
    assert uploaded["filename"].endswith(".zip")

    zf = zipfile.ZipFile(io.BytesIO(uploaded["zip"]))
    names = zf.namelist()
    assert names == sorted(names), "ZIP entries should be deterministic and sorted"
    assert "Audit_Evidence_Pack/00_README/pack_overview.pdf" in names
    assert "Audit_Evidence_Pack/01_EXECUTIVE_SUMMARY/compliance_summary.pdf" in names
    assert "Audit_Evidence_Pack/06_GOVERNANCE/manifest.json" in names
    assert "Audit_Evidence_Pack/06_GOVERNANCE/checksums.sha256" in names
    assert "Audit_Evidence_Pack/06_GOVERNANCE/generation_metadata.json" in names
    assert "Audit_Evidence_Pack/07_EXCEPTIONS/missing_or_pending_items.json" in names

    manifest = json.loads(zf.read("Audit_Evidence_Pack/06_GOVERNANCE/manifest.json").decode("utf-8"))
    metadata = json.loads(zf.read("Audit_Evidence_Pack/06_GOVERNANCE/generation_metadata.json").decode("utf-8"))
    exceptions = json.loads(zf.read("Audit_Evidence_Pack/07_EXCEPTIONS/missing_or_pending_items.json").decode("utf-8"))
    checksums = zf.read("Audit_Evidence_Pack/06_GOVERNANCE/checksums.sha256").decode("utf-8")

    assert metadata["export_version"] == "2026.04"
    assert metadata["evidence_pack_version"] == "2.0.0"
    assert metadata["source_registry_version"] == "1"
    assert "Audit_Evidence_Pack/01_EXECUTIVE_SUMMARY/compliance_summary.pdf" in checksums
    assert "files" in manifest and len(manifest["files"]) > 0
    assert "ghost_hidden_1" in manifest["excluded_non_runtime_visible_requirement_ids"]
    assert any(x.get("requirement_id") == "ghost_hidden_1" for x in exceptions["excluded_historical_items"])

