"""ClearForm PDF Service

Generates professional PDFs from document content.
Uses reportlab for PDF generation.
"""

from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch, cm
from reportlab.lib.enums import TA_LEFT, TA_CENTER, TA_JUSTIFY
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, PageBreak
from reportlab.lib.colors import HexColor
from io import BytesIO
from datetime import datetime
import re
import logging

logger = logging.getLogger(__name__)


class PDFService:
    """PDF generation service for ClearForm documents."""
    
    def __init__(self):
        self._styles = None
    
    def _get_styles(self):
        """Get styles (lazy init to avoid duplicate names)."""
        styles = getSampleStyleSheet()
        
        # Override BodyText instead of adding
        styles['BodyText'].fontSize = 11
        styles['BodyText'].leading = 16
        styles['BodyText'].spaceBefore = 6
        styles['BodyText'].spaceAfter = 6
        styles['BodyText'].alignment = TA_JUSTIFY
        styles['BodyText'].textColor = HexColor('#374151')
        
        # Title style
        styles.add(ParagraphStyle(
            name='DocTitle',
            parent=styles['Heading1'],
            fontSize=18,
            spaceAfter=20,
            textColor=HexColor('#1e293b'),
            alignment=TA_CENTER,
        ))
        
        # Section heading
        styles.add(ParagraphStyle(
            name='SectionHead',
            parent=styles['Heading2'],
            fontSize=14,
            spaceBefore=15,
            spaceAfter=8,
            textColor=HexColor('#334155'),
        ))
        
        # Date/header text
        styles.add(ParagraphStyle(
            name='DateText',
            parent=styles['Normal'],
            fontSize=10,
            textColor=HexColor('#6b7280'),
            alignment=TA_LEFT,
        ))
        
        # Address block
        styles.add(ParagraphStyle(
            name='Address',
            parent=styles['Normal'],
            fontSize=11,
            leading=14,
            spaceBefore=3,
            spaceAfter=3,
            textColor=HexColor('#374151'),
        ))
        
        # Signature line
        styles.add(ParagraphStyle(
            name='Signature',
            parent=styles['Normal'],
            fontSize=11,
            spaceBefore=20,
            textColor=HexColor('#374151'),
        ))
        
        return styles
    
    def generate_pdf(self, title: str, content: str, document_type: str = None) -> bytes:
        """Generate PDF from document content.
        
        Args:
            title: Document title
            content: Markdown or plain text content
            document_type: Type of document for styling hints
            
        Returns:
            PDF bytes
        """
        buffer = BytesIO()
        
        doc = SimpleDocTemplate(
            buffer,
            pagesize=A4,
            rightMargin=2*cm,
            leftMargin=2*cm,
            topMargin=2*cm,
            bottomMargin=2*cm,
        )
        
        story = []
        
        # Add title
        story.append(Paragraph(self._escape_html(title), self.styles['DocTitle']))
        story.append(Spacer(1, 0.3*inch))
        
        # Parse and add content
        content_elements = self._parse_content(content)
        story.extend(content_elements)
        
        # Add footer with generation info
        story.append(Spacer(1, 0.5*inch))
        footer_text = f"Generated by ClearForm on {datetime.now().strftime('%d %B %Y')}"
        story.append(Paragraph(footer_text, self.styles['DateText']))
        
        doc.build(story)
        
        pdf_bytes = buffer.getvalue()
        buffer.close()
        
        return pdf_bytes
    
    def _parse_content(self, content: str) -> list:
        """Parse markdown-like content into PDF elements."""
        elements = []
        
        # Clean up code fences
        content = re.sub(r'^```(?:markdown)?\s*\n?', '', content, flags=re.IGNORECASE)
        content = re.sub(r'\n?```\s*$', '', content, flags=re.IGNORECASE)
        
        lines = content.split('\n')
        current_paragraph = []
        
        for line in lines:
            stripped = line.strip()
            
            # Skip empty lines - flush current paragraph
            if not stripped:
                if current_paragraph:
                    text = ' '.join(current_paragraph)
                    elements.append(Paragraph(self._escape_html(text), self.styles['BodyText']))
                    current_paragraph = []
                elements.append(Spacer(1, 0.1*inch))
                continue
            
            # Headers (## or ###)
            if stripped.startswith('###'):
                if current_paragraph:
                    text = ' '.join(current_paragraph)
                    elements.append(Paragraph(self._escape_html(text), self.styles['BodyText']))
                    current_paragraph = []
                header_text = stripped.lstrip('#').strip()
                elements.append(Paragraph(self._escape_html(header_text), self.styles['SectionHead']))
                continue
            
            if stripped.startswith('##'):
                if current_paragraph:
                    text = ' '.join(current_paragraph)
                    elements.append(Paragraph(self._escape_html(text), self.styles['BodyText']))
                    current_paragraph = []
                header_text = stripped.lstrip('#').strip()
                elements.append(Paragraph(self._escape_html(header_text), self.styles['SectionHead']))
                continue
            
            if stripped.startswith('#'):
                if current_paragraph:
                    text = ' '.join(current_paragraph)
                    elements.append(Paragraph(self._escape_html(text), self.styles['BodyText']))
                    current_paragraph = []
                header_text = stripped.lstrip('#').strip()
                elements.append(Paragraph(self._escape_html(header_text), self.styles['DocTitle']))
                continue
            
            # Bold markers **text** -> <b>text</b>
            if '**' in stripped:
                stripped = re.sub(r'\*\*(.+?)\*\*', r'<b>\1</b>', stripped)
            
            # Italic markers *text* -> <i>text</i>
            if '*' in stripped:
                stripped = re.sub(r'\*(.+?)\*', r'<i>\1</i>', stripped)
            
            # Bullet points
            if stripped.startswith('- ') or stripped.startswith('* '):
                if current_paragraph:
                    text = ' '.join(current_paragraph)
                    elements.append(Paragraph(self._escape_html(text), self.styles['BodyText']))
                    current_paragraph = []
                bullet_text = '• ' + stripped[2:]
                elements.append(Paragraph(bullet_text, self.styles['BodyText']))
                continue
            
            # Date patterns at start of document
            if re.match(r'^\d{1,2}(?:st|nd|rd|th)?\s+\w+\s+\d{4}', stripped) or \
               re.match(r'^\w+\s+\d{1,2},?\s+\d{4}', stripped):
                if current_paragraph:
                    text = ' '.join(current_paragraph)
                    elements.append(Paragraph(self._escape_html(text), self.styles['BodyText']))
                    current_paragraph = []
                elements.append(Paragraph(self._escape_html(stripped), self.styles['DateText']))
                continue
            
            # Regular text - accumulate
            current_paragraph.append(stripped)
        
        # Flush any remaining paragraph
        if current_paragraph:
            text = ' '.join(current_paragraph)
            elements.append(Paragraph(self._escape_html(text), self.styles['BodyText']))
        
        return elements
    
    def _escape_html(self, text: str) -> str:
        """Escape HTML special characters except for allowed tags."""
        # Don't escape if it contains allowed formatting tags
        if '<b>' in text or '<i>' in text or '<u>' in text:
            # Only escape & < > that aren't part of tags
            text = text.replace('&', '&amp;')
            # Be careful not to escape valid tags
            return text
        
        # Full escape
        return (text
            .replace('&', '&amp;')
            .replace('<', '&lt;')
            .replace('>', '&gt;')
        )


# Global instance
pdf_service = PDFService()
