"""
Operational Evidence Platform — stable enums and catalogues.

Distinct from client-facing compliance_timeline (requirement dates).
This platform indexes runtime operational evidence from authoritative sources.
"""
from __future__ import annotations

# --- Categories (timeline filter axis) ---

CATEGORY_SCHEDULER = "scheduler"
CATEGORY_QUEUE = "queue"
CATEGORY_WORKER = "worker"
CATEGORY_COMPLIANCE = "compliance"
CATEGORY_RISK = "risk"
CATEGORY_REMINDER = "reminder"
CATEGORY_NOTIFICATION = "notification"
CATEGORY_SMS = "sms"
CATEGORY_EMAIL = "email"
CATEGORY_WEBHOOK = "webhook"
CATEGORY_REPORT = "report"
CATEGORY_DOCUMENT = "document"
CATEGORY_SUBSCRIPTION = "subscription"
CATEGORY_PAYMENT = "payment"
CATEGORY_EVIDENCE = "evidence"
CATEGORY_PROPERTY = "property"
CATEGORY_PORTFOLIO = "portfolio"
CATEGORY_WORKFLOW = "workflow"
CATEGORY_INCIDENT = "incident"
CATEGORY_RECOVERY = "recovery"
CATEGORY_DEPLOYMENT = "deployment"
CATEGORY_SECURITY = "security"
CATEGORY_AUTHENTICATION = "authentication"
CATEGORY_API = "api"
CATEGORY_ADMINISTRATION = "administration"
CATEGORY_CUSTOMER_ACTIVITY = "customer_activity"
CATEGORY_SYSTEM_HEALTH = "system_health"
CATEGORY_PLATFORM_STATUS = "platform_status"
CATEGORY_OBSERVABILITY = "observability"

ALL_CATEGORIES = frozenset(
    {
        CATEGORY_SCHEDULER,
        CATEGORY_QUEUE,
        CATEGORY_WORKER,
        CATEGORY_COMPLIANCE,
        CATEGORY_RISK,
        CATEGORY_REMINDER,
        CATEGORY_NOTIFICATION,
        CATEGORY_SMS,
        CATEGORY_EMAIL,
        CATEGORY_WEBHOOK,
        CATEGORY_REPORT,
        CATEGORY_DOCUMENT,
        CATEGORY_SUBSCRIPTION,
        CATEGORY_PAYMENT,
        CATEGORY_EVIDENCE,
        CATEGORY_PROPERTY,
        CATEGORY_PORTFOLIO,
        CATEGORY_WORKFLOW,
        CATEGORY_INCIDENT,
        CATEGORY_RECOVERY,
        CATEGORY_DEPLOYMENT,
        CATEGORY_SECURITY,
        CATEGORY_AUTHENTICATION,
        CATEGORY_API,
        CATEGORY_ADMINISTRATION,
        CATEGORY_CUSTOMER_ACTIVITY,
        CATEGORY_SYSTEM_HEALTH,
        CATEGORY_PLATFORM_STATUS,
        CATEGORY_OBSERVABILITY,
    }
)

# --- Relationship types (causality graph edges) ---

REL_TRIGGERED = "triggered"
REL_CAUSED = "caused"
REL_CHILD_OF = "child_of"
REL_RETRY_OF = "retry_of"
REL_RECOVERED_FROM = "recovered_from"
REL_CORRELATED = "correlated"
REL_CONTINUATION = "continuation"
REL_DUPLICATE_DETECTION = "duplicate_detection"

# --- Infrastructure event types ---

EVT_JOB_RUN_STARTED = "JOB_RUN_STARTED"
EVT_JOB_RUN_COMPLETED = "JOB_RUN_COMPLETED"
EVT_JOB_RUN_FAILED = "JOB_RUN_FAILED"
EVT_JOB_RUN_DEGRADED = "JOB_RUN_DEGRADED"
EVT_QUEUE_ITEM_CREATED = "QUEUE_ITEM_CREATED"
EVT_QUEUE_ITEM_CLAIMED = "QUEUE_ITEM_CLAIMED"
EVT_QUEUE_ITEM_COMPLETED = "QUEUE_ITEM_COMPLETED"
EVT_QUEUE_ITEM_FAILED = "QUEUE_ITEM_FAILED"
EVT_QUEUE_ITEM_DEAD = "QUEUE_ITEM_DEAD"
EVT_INCIDENT_OPENED = "INCIDENT_OPENED"
EVT_INCIDENT_DEGRADED = "INCIDENT_DEGRADED"
EVT_INCIDENT_RECOVERED = "INCIDENT_RECOVERED"
EVT_INCIDENT_RESOLVED = "INCIDENT_RESOLVED"
EVT_INCIDENT_REPEAT_DETECTED = "INCIDENT_REPEAT_DETECTED"
EVT_NOTIFICATION_QUEUED = "NOTIFICATION_QUEUED"
EVT_NOTIFICATION_SENT = "NOTIFICATION_SENT"
EVT_NOTIFICATION_FAILED = "NOTIFICATION_FAILED"
EVT_NOTIFICATION_RETRY_SCHEDULED = "NOTIFICATION_RETRY_SCHEDULED"
EVT_HEARTBEAT_STALE = "HEARTBEAT_STALE"
EVT_SLA_BREACH_DETECTED = "SLA_BREACH_DETECTED"

# --- Business domain event types (Phase 7 catalogue) ---

EVT_COMPLIANCE_BECAME_VALID = "COMPLIANCE_BECAME_VALID"
EVT_COMPLIANCE_BECAME_NON_COMPLIANT = "COMPLIANCE_BECAME_NON_COMPLIANT"
EVT_REQUIREMENT_CREATED = "REQUIREMENT_CREATED"
EVT_REQUIREMENT_REMOVED = "REQUIREMENT_REMOVED"
EVT_REQUIREMENT_EXPIRED = "REQUIREMENT_EXPIRED"
EVT_EVIDENCE_UPLOADED = "EVIDENCE_UPLOADED"
EVT_EVIDENCE_APPROVED = "EVIDENCE_APPROVED"
EVT_EVIDENCE_REJECTED = "EVIDENCE_REJECTED"
EVT_PORTFOLIO_RISK_INCREASED = "PORTFOLIO_RISK_INCREASED"
EVT_PORTFOLIO_RISK_DECREASED = "PORTFOLIO_RISK_DECREASED"
EVT_COMPLIANCE_SCORE_CHANGED = "COMPLIANCE_SCORE_CHANGED"
EVT_REMINDER_GENERATED = "REMINDER_GENERATED"
EVT_REMINDER_COMPLETED = "REMINDER_COMPLETED"
EVT_WORK_ORDER_OPENED = "WORK_ORDER_OPENED"
EVT_WORK_ORDER_COMPLETED = "WORK_ORDER_COMPLETED"
EVT_INSPECTION_SCHEDULED = "INSPECTION_SCHEDULED"
EVT_INSPECTION_COMPLETED = "INSPECTION_COMPLETED"

BUSINESS_EVENT_TYPES = frozenset(
    {
        EVT_COMPLIANCE_BECAME_VALID,
        EVT_COMPLIANCE_BECAME_NON_COMPLIANT,
        EVT_REQUIREMENT_CREATED,
        EVT_REQUIREMENT_REMOVED,
        EVT_REQUIREMENT_EXPIRED,
        EVT_EVIDENCE_UPLOADED,
        EVT_EVIDENCE_APPROVED,
        EVT_EVIDENCE_REJECTED,
        EVT_PORTFOLIO_RISK_INCREASED,
        EVT_PORTFOLIO_RISK_DECREASED,
        EVT_COMPLIANCE_SCORE_CHANGED,
        EVT_REMINDER_GENERATED,
        EVT_REMINDER_COMPLETED,
        EVT_WORK_ORDER_OPENED,
        EVT_WORK_ORDER_COMPLETED,
        EVT_INSPECTION_SCHEDULED,
        EVT_INSPECTION_COMPLETED,
    }
)

# --- Customer impact classifications ---

IMPACT_NONE = "no_impact"
IMPACT_OPERATIONAL_ONLY = "operational_only"
IMPACT_DELAYED = "delayed"
IMPACT_TEMPORARILY_STALE = "temporarily_stale"
IMPACT_READ_ONLY_DEGRADATION = "read_only_degradation"
IMPACT_PARTIAL = "partial_customer_impact"
IMPACT_PROPERTY = "property_affected"
IMPACT_PORTFOLIO = "portfolio_affected"
IMPACT_MULTI_TENANT = "multiple_tenants_affected"
IMPACT_INCORRECT_OUTPUT = "incorrect_output"
IMPACT_RECOVERED_AUTO = "recovered_automatically"
IMPACT_RECOVERED_MANUAL = "recovered_manually"
IMPACT_MANUAL_REQUIRED = "manual_intervention_required"

ALL_IMPACT_CLASSIFICATIONS = frozenset(
    {
        IMPACT_NONE,
        IMPACT_OPERATIONAL_ONLY,
        IMPACT_DELAYED,
        IMPACT_TEMPORARILY_STALE,
        IMPACT_READ_ONLY_DEGRADATION,
        IMPACT_PARTIAL,
        IMPACT_PROPERTY,
        IMPACT_PORTFOLIO,
        IMPACT_MULTI_TENANT,
        IMPACT_INCORRECT_OUTPUT,
        IMPACT_RECOVERED_AUTO,
        IMPACT_RECOVERED_MANUAL,
        IMPACT_MANUAL_REQUIRED,
    }
)

# Legacy scope mapping (backward compatible with proposal v1)
IMPACT_SCOPE_NONE = "none"
IMPACT_SCOPE_PROPERTY = "property"
IMPACT_SCOPE_PORTFOLIO = "portfolio"
IMPACT_SCOPE_TENANT = "tenant"
IMPACT_SCOPE_PLATFORM = "platform"

# --- Confidence levels ---

CONFIDENCE_RUNTIME_CONFIRMED = 100
CONFIDENCE_MULTI_SOURCE = 95
CONFIDENCE_INDIRECT = 80
CONFIDENCE_PROVIDER_PENDING = 60
CONFIDENCE_INFERENCE_ONLY = 40

CONFIDENCE_LABELS = {
    CONFIDENCE_RUNTIME_CONFIRMED: "runtime_confirmed",
    CONFIDENCE_MULTI_SOURCE: "multi_source_agreement",
    CONFIDENCE_INDIRECT: "indirect_runtime_confirmation",
    CONFIDENCE_PROVIDER_PENDING: "provider_acknowledgement_pending",
    CONFIDENCE_INFERENCE_ONLY: "inference_only",
}

COLLECTION_EVENTS = "operational_evidence_events"
COLLECTION_ANNOTATIONS = "operational_evidence_annotations"
COLLECTION_EXECUTIONS = "operational_evidence_executions"
